### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by su-heyang** [THUDM/ChatGLM2-6B#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我使用本地模型路径，但仍然去.cache/huggingface/目录里去找模型文件，从而找不到模型文件

### Steps To Reproduce

run `python cli_demo.py`
error:
Traceback (most recent call last):
  File "cli_demo.py", line 11, in <module>
    tokenizer = AutoTokenizer.from_pretrained("/home/admin/chatglm2-6b", trust_remote_code=True)
  File "/home/admin/anaconda3/envs/glm2/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 678, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/admin/anaconda3/envs/glm2/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
    return cls._from_pretrained(
  File "/home/admin/anaconda3/envs/glm2/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1988, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/admin/.cache/huggingface/modules/transformers_modules/chatglm2-6b/tokenization_chatglm.py", line 73, in __init__
    self.tokenizer = SPTokenizer(vocab_file)
  File "/home/admin/.cache/huggingface/modules/transformers_modules/chatglm2-6b/tokenization_chatglm.py", line 13, in __init__
    assert os.path.isfile(model_path), model_path
  File "/home/admin/anaconda3/envs/glm2/lib/python3.8/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### Environment

```markdown
- OS:Ubuntu 18.04
- Python:3.8
- Transformers:4.30.2
- PyTorch:2.0.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by su-heyang** [comment]
已解决，模型文件缺失tokenier.model

**Comment by Jan06Chen** [comment]
> tokenier.model

解决了，你把解决办法 贴出来的
