### ISSUE TITLE
[Help] torch.cuda.OutOfMemoryError: CUDA out of memory. 但是其实还有大量free的VRAM没有分配

### ISSUE THREAD

**Issue by OpenAndrus** [THUDM/ChatGLM2-6B#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB (GPU 0; 22.00 GiB total capacity; 3.06 GiB already allocated; 17.34 GiB free; 3.06 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CON

### Steps To Reproduce

显卡是2080TI 22G，显示还有17G多free却OOM
环境：
pytorch-cuda=11.8
pytorch=2.0.1

### Environment

```markdown
- OS:Ubuntu 22.04.2 LTS
- Python: 3.11.4
- Transformers: 4.27.1
- PyTorch:2.0.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by arkerwu** [comment]
魔改显卡~训练最多用11G;

**Comment by OpenAndrus** [comment]
> 魔改显卡~训练最多用11G;

这也没用到11G啊

**Comment by duzx16** [comment]
2080 Ti 只有 11 GB 显存吧

**Comment by ferdyzhang** [comment]
同样问题，怎么解决呢？？
OutOfMemoryError: CUDA out of memory. Tried to allocate 508.00 MiB (GPU 0; 11.76 GiB total capacity; 11.16 GiB already allocated; 488.19 MiB free; 11.16 GiB reserved in total by PyTorch) If
reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by duzx16** [comment]
@ferdyzhang 11GB 跑不了 fp16 的模型，可以用 [chatglm2-int4](https://huggingface.co/THUDM/chatglm2-6b-int4)

**Comment by mikeleatila** [comment]
Hi, has this been finally solved? And how? I am still getting the same issue:

OS: Ubuntu 20.04
Python: 3.10
Transformers: 4.27.1 or 4.30.2
PyTorch: 2.0.1
CUDA Support: True

I am using 2 Tesla V100 GPUs with 32GB of memory.


So when running: 

deepspeed --num_gpus=2 main.py --deepspeed deepspeed.json --do_train --train_file Data/train.json --test_file Data/test.json --prompt_column prompt --response_column response --overwrite_cache --model_name_or_path THUDM/chatglm2-6b --output_dir ./output/ada-chatglm2-6b-pt-128-1e-4 --overwrite_output_dir --max_source_length 550 --max_target_length 16 --per_device_train_batch_size 2 --per_device_eval_batch_size 1  --gradient_accumulation_steps 1 --predict_with_generate --max_steps 1000000 --logging_steps 10 --save_steps 10 --learning_rate 1e-4 --fp16


there is the error:

[2023-07-13 21:11:25,319] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed info: version=0.9.5, git-hash=unknown, git-branch=unknown
[INFO|trainer.py:597] 2023-07-13 21:11:25,312 >> Using cuda_amp half precision backend
/home/ppp/anaconda3/envs/chatglm2/lib/python3.10/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
[2023-07-13 21:11:32,256] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
[2023-07-13 21:11:32,256] [INFO] [logging.py:96:log_dist] [Rank 0] Removing param_group that has no 'params' in the client Optimizer
[2023-07-13 21:11:32,256] [INFO] [logging.py:96:log_dist] [Rank 0] Using client Optimizer as basic optimizer
[2023-07-13 21:11:32,262] [INFO] [logging.py:96:log_dist] [Rank 0] DeepSpeed Basic Optimizer = AdamW
[2023-07-13 21:11:32,262] [INFO] [utils.py:54:is_zero_supported_optimizer] Checking ZeRO support for optimizer=AdamW type=<class 'transformers.optimization.AdamW'>
[2023-07-13 21:11:32,262] [WARNING] [engine.py:1115:_do_optimizer_sanity_check] **** You are using ZeRO with an untested optimizer, proceed with caution *****
[2023-07-13 21:11:32,262] [INFO] [logging.py:96:log_dist] [Rank 0] Creating torch.float16 ZeRO stage 2 optimizer
[2023-07-13 21:11:32,262] [INFO] [stage_1_and_2.py:133:__init__] Reduce bucket size 500000000
[2023-07-13 21:11:32,262] [INFO] [stage_1_and_2.py:134:__init__] Allgather bucket size 500000000
[2023-07-13 21:11:32,262] [INFO] [stage_1_and_2.py:135:__init__] CPU Offload: False
[2023-07-13 21:11:32,262] [INFO] [stage_1_and_2.py:136:__init__] Round robin gradient partitioning: False
Traceback (most recent call last):
  File "/home/ppp/ChatGLM2-6B/ptuning/main.py", line 427, in <module>
    main()
  File "/home/ppp/ChatGLM2-6B/ptuning/main.py", line 366, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/ppp/anaconda3/envs/chatglm2/lib/python3.10/site-packages/transformers/trainer.py", line 1633, in train
    return inner_training_loop(
  File "/home/ppp/anaconda3/envs/chatglm2/lib/python3.10/site-packages/transformers/trainer.py", line 1702, in _inner_training_loop
    deepspeed_engine, optimizer, lr_scheduler = deepspeed_init(
  File "/home/ppp/anaconda3/envs/chatglm2/lib/python3.10/site-packages/transformers/deepspeed.py", line 378, in deepspeed_init
    deepspeed_engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/home/ppp/anaconda3/envs/chatglm2/lib/python3.10/site-packages/deepspeed/__init__.py", line 165, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/ppp/anaconda3/envs/chatglm2/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 309, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/ppp/anaconda3/envs/chatglm2/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1184, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/ppp/anaconda3/envs/chatglm2/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1419, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer(
  File "/home/ppp/anaconda3/envs/chatglm2/lib/python3.10/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 346, in __init__
    self.device).clone().float().detach())
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 23.26 GiB (GPU 0; 31.74 GiB total capacity; 23.26 GiB already allocated; 7.64 GiB free; 23.26 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF


Many thanks in advance!

**Comment by mikeleatila** [comment]
Thanks a lot @ferdyzhang , sorry I did not get any notification about your reply. I am using a machine. How can I check which processes occupy the video memory on the machine and kill them? Again sorry for my late reply.

**Comment by mikeleatila** [comment]
@ferdyzhang Even when I try with 4 GPUs, i.e. 4 Tesla V100 GPUs with 32GB of memory I also get torch.cuda.OutOfMemoryError: CUDA out of memory errors.
