### ISSUE TITLE
从本地加载模型报错

### ISSUE THREAD

**Issue by ponponon** [THUDM/ChatGLM2-6B#115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```python
from transformers import AutoTokenizer, AutoModel
from loguru import logger
import time

tokenizer = AutoTokenizer.from_pretrained(
    "THUDM/chatglm2-6b-int4", trust_remote_code=True)
# model = AutoModel.from_pretrained(
#     "THUDM/chatglm2-6b", trust_remote_code=True, device='cuda')

model = AutoModel.from_pretrained("/Volumes/MyPassport/迅雷下载/pytorch_model.bin", trust_remote_code=True).to('mps')


model = model.eval()
```

报错输出

```
Traceback (most recent call last):
  File "/Users/ponponon/Desktop/code/me/transformers_example/1.py", line 5, in <module>
    tokenizer = AutoTokenizer.from_pretrained(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ponponon/.local/share/virtualenvs/transformers_example-k-TvNpxm/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 643, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ponponon/.local/share/virtualenvs/transformers_example-k-TvNpxm/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 487, in get_tokenizer_config
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "/Users/ponponon/.local/share/virtualenvs/transformers_example-k-TvNpxm/lib/python3.11/site-packages/transformers/utils/hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "/Users/ponponon/.local/share/virtualenvs/transformers_example-k-TvNpxm/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "/Users/ponponon/.local/share/virtualenvs/transformers_example-k-TvNpxm/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/Volumes/MyPassport/迅雷下载/pytorch_model.bin'. Use `repo_type` argument if needed.

```

所以如何设置本地的路径？应该存放在哪里？如何命名？

### Expected Behavior

run

### Steps To Reproduce

e

### Environment

```markdown
- OS: mac 
- Python: 3.10
- Transformers: 4.30.1
- PyTorch: 2.0.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : no, is mps
```

### Anything else?

no

**Comment by int-yscwl** [comment]
我不太清楚你把你的模型放在哪个文件夹下了，我是放在ChatGLM2-6B中THUDM的文件夹下（自己建一个THUDM文件夹就行）
拿web_demo.py来进行说明，里面有两个路径需要更改，在第6、7行的地方，将其改成
tokenizer = AutoTokenizer.from_pretrained("THUDM", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM", trust_remote_code=True).cuda()
即可，删除/chatglm2-6b就行。

**Comment by qinchaofeng** [comment]
不用带后面的模型文件名称 pytorch_model.bin

**Comment by ThankyouEverybody** [comment]
<img width="1014" alt="image" src="https://github.com/THUDM/ChatGLM2-6B/assets/38928746/6967301e-0d79-4912-bfc0-1cbb765812bb">
我把模型地址拿出来 就好了  你可以试试
