### ISSUE TITLE
[BUG/Help] <Windows CPU 无法启用多核并行运算 --> quantization_kernels_parallels.so>

### ISSUE THREAD

**Issue by YifuLiu-uk** [THUDM/ChatGLM2-6B#121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Log 如下：

Failed to load cpm_kernels:name 'CPUKernel' is not defined

Load parallel cpu kernel failed C:\Users\admin\ .cache\huggingface\modules\transformers_modules\Chatglm2-6b-int4\quantization_kernels_parallel.so: Traceback (most recent call last):
File "C:\Users\admin/.cache\huggingface\modules\transformers_modules\Chatglm2-6b-int4\quantization.py", line 138, in init
kernels = ctypes.cdll.LoadLibrary(kernel_file)
File "C:\Users\admin\anaconda3\lib\ctypes_init_.py", line 452, in LoadLibrary
return self.dlltype(name)
File "C:\Users\admin\anaconda3\lib\ctypes_init.py", line 374, in init
self._handle = _dlopen(self._name, mode)

FileNotFoundError: Could not find module 'C:\Users\admin\ .cache\huggingface\modules\transformers_modules\Chatglm2-6b-int4\quantization_kernels_parallel.so' (or one of its dependencies). Try using the full path with constructor syntax.

### Expected Behavior

Activating CPU-based kernels parallel computing / 启动CPU多核并行运算

### Steps To Reproduce

1. 已经按照教程将模型下载至本地并使用本地路径
2. 已按教程改用.float()使用cpu --> model = AutoModel.from_pretrained("local_address",trust_remote_code=True).float()
3. 已安装[TDM-GCC](https://jmeubank.github.io/tdm-gcc/) --> TDM-GCC 10.3.0 与 openmp
4. 已注释掉“from cpm_kernels.kernels.base import LazyKernelCModule, KernelFunction, round_up”
5. 已将“kernels = Kernel(****)”改成“kernels = CPUKernel()”
6. 主要参考ChatGLM-6B中的：[Issue 166](https://github.com/THUDM/ChatGLM-6B/issues/166)和[Issue 529](https://github.com/THUDM/ChatGLM-6B/issues/529)
7. quantization_kernels_parallel.so 手动载入失败，quantization_kernels.so载入正常
8. 
![d0ade63381c981f6ce6d60d67d64c53](https://github.com/THUDM/ChatGLM2-6B/assets/59554407/ed01dbe9-adc8-4f10-baa1-f295822ca5d4)

### Environment

```markdown
- OS: Windows
- Python: 3.8.16
- Transformers: 4.30.2
- PyTorch: 2.0.1+cpu
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : False
```

### Anything else?

目前报错:

NameError: name 'CPUKernel' is not defined
Load parallel cpu kernel failed --> quantization_kernels_parallel.so
可以运行quantization_kernels.so，但无法运行quantization_kernels_parallel.so
希望多核心并行运算，有啥好办法吗，谢谢大家

**Comment by jackaihfia2334** [comment]
同quantization_kernels_parallel.so 手动载入失败，quantization_kernels.so载入正常

**Comment by chandler971017** [comment]
同样有这个问题, 好像模型最后还是能加载, 应该是跳过了这一段逻辑.

**Comment by gavinju** [comment]
同样上面的报错，请问解决了吗？ 我的报错最后还有一行：RuntimeError: CUDA Error: no kernel image is available for execution on the device
