### ISSUE TITLE
[BUG/Help] 本地加载模型时报错

### ISSUE THREAD

**Issue by fishlary** [THUDM/ChatGLM2-6B#136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Python中使用Readme 代码调用部分的例子测试模型的时候,执行到
```Python
model = AutoModel.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True, device='cuda')
```
这一行的时候报错,具体错误信息如下
```Python
>>> from transformers import AutoTokenizer, AutoModelForCausalLM
>>> local_model_path = "model/chatglm2-6b"
>>> tokenizer = AutoTokenizer.from_pretrained(local_model_path, trust_remote_code=True)
normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.
>>> model = AutoModelForCausalLM.from_pretrained(local_model_path, trust_remote_code=True, device='cuda')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 487, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.chatglm2-6b.configuration_chatglm.ChatGLMConfig'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, TransfoXLConfig, TrOCRConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.
>>>
 ```

可能是什么原因造成的,需要如何调整

### Expected Behavior

应该能正常加载模型?

### Steps To Reproduce

```Python
>>> from transformers import AutoTokenizer, AutoModelForCausalLM
>>> local_model_path = "model/chatglm2-6b"
>>> tokenizer = AutoTokenizer.from_pretrained(local_model_path, trust_remote_code=True)
normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.
>>> model = AutoModelForCausalLM.from_pretrained(local_model_path, trust_remote_code=True, device='cuda')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 487, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.chatglm2-6b.configuration_chatglm.ChatGLMConfig'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, TransfoXLConfig, TrOCRConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.
>>>
 ```

### Environment

```markdown
- OS:
- Python: 3.10.10
- Transformers: 4.30.2 
- PyTorch: 2.0.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by iunique** [comment]
我也出现了这个问题，请问应该怎么解决呢

**Comment by xiaowei4895** [comment]
可以尝试删除“/home/用户名/.cache/huggingface/hub/models--THUDM--chatglm2-6b“，重新下载模型试试。
