### ISSUE TITLE
[BUG/Help] 大佬们请帮我看看昨天都能用 今天报错 AttributeError: 'NoneType' object has no attribute 'int4WeightExtractionHalf'

### ISSUE THREAD

**Issue by JohnHsiao1** [THUDM/ChatGLM2-6B#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("D:\\AI\\chatmodel\\chatglm2-6b-int4", trust_remote_code=True, revision="")
model = AutoModel.from_pretrained("D:\\AI\\chatmodel\\chatglm2-6b-int4", trust_remote_code=True, revision="").half().cuda()
model = model.eval()
result,_ = model.chat(tokenizer, "你好", history=[])
print(result)

运行最基础的代码都报错...
AttributeError: 'NoneType' object has no attribute 'int4WeightExtractionHalf'

### Steps To Reproduce

from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("D:\\AI\\chatmodel\\chatglm2-6b-int4", trust_remote_code=True, revision="")
model = AutoModel.from_pretrained("D:\\AI\\chatmodel\\chatglm2-6b-int4", trust_remote_code=True, revision="").half().cuda()
model = model.eval()
result,_ = model.chat(tokenizer, "你好", history=[])
print(result)

AttributeError: 'NoneType' object has no attribute 'int4WeightExtractionHalf'

### Environment

```markdown
- OS:win11
- Python:3.11.1
- Transformers:4.26.1
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by duzx16** [comment]
编译 CPU 上的量化 kernel失败了，具体原因要看之前的报错信息

**Comment by zzzgydi** [comment]
> 编译 CPU 上的量化 kernel失败了，具体原因要看之前的报错信息

之前的报错信息是下面这样的

```
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: f5339951-6c5c-4519-9232-5e402d6634c6)')' thrown while requesting HEAD https://huggingface.co/THUDM/chatglm2-6b-int4/resolve/main/config.json
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: f684f8ef-bf82-4aac-859b-e7d90dd0c408)')' thrown while requesting HEAD https://huggingface.co/THUDM/chatglm2-6b-int4/resolve/main/configuration_chatglm.py
/Users/-/Library/Python/3.9/lib/python/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
Failed to load cpm_kernels:Unknown platform: darwin
/Users/-/.cache/huggingface/modules/transformers_modules/THUDM/chatglm2-6b-int4/382cc704867dc2b78368576166799ace0f89d9ef/quantization_kernels_parallel.c:1:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
Compile parallel cpu kernel clang -O3 -fPIC -pthread -Xclang -fopenmp -lomp -std=c99 /Users/-/.cache/huggingface/modules/transformers_modules/THUDM/chatglm2-6b-int4/382cc704867dc2b78368576166799ace0f89d9ef/quantization_kernels_parallel.c -shared -o /Users/-/.cache/huggingface/modules/transformers_modules/THUDM/chatglm2-6b-int4/382cc704867dc2b78368576166799ace0f89d9ef/quantization_kernels_parallel.so failed.
2023-08-16 17:34:51.613 Uncaught app exception

```

**Comment by aWindTalker** [comment]
Failed to load cpm_kernels:[WinError 267] 目录名称无效。: 'D:\\software\\inkscape\\bin\\inkscape.exe'
c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../../mingw32/bin/ld.exe: cannot find -lpthread
collect2.exe: error: ld returned 1 exit status
Compile parallel cpu kernel gcc -O3 -fPIC -pthread -fopenmp -std=c99 C:\Users\mzw\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization_kernels_parallel.c -shared -o C:\Users\mzw\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization_kernels_parallel.so failed.
Load cpu kernel C:\Users\mzw\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization_kernels.so failed: Traceback (most recent call last):
  File "C:\Users\mzw/.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization.py", line 165, in __init__     
    kernels = ctypes.cdll.LoadLibrary(kernel_file)
  File "C:\Users\mzw\.conda\envs\ChatGLM\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\mzw\.conda\envs\ChatGLM\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

d:\ChatGLM\ChatGLM2-6B\web_demo.py:90: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  user_input = gr.Textbox(show_label=False, placeholder="Input...", lines=10).style(
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\Users\mzw\.conda\envs\ChatGLM\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\mzw\.conda\envs\ChatGLM\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\Users\mzw\.conda\envs\ChatGLM\lib\site-packages\gradio\blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\mzw\.conda\envs\ChatGLM\lib\site-packages\gradio\utils.py", line 349, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\mzw\.conda\envs\ChatGLM\lib\site-packages\gradio\utils.py", line 342, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\mzw\.conda\envs\ChatGLM\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\mzw\.conda\envs\ChatGLM\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread   
    return await future
  File "C:\Users\mzw\.conda\envs\ChatGLM\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\mzw\.conda\envs\ChatGLM\lib\site-packages\gradio\utils.py", line 325, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\mzw\.conda\envs\ChatGLM\lib\site-packages\gradio\utils.py", line 694, in gen_wrapper
    yield from f(*args, **kwargs)
  File "d:\ChatGLM\ChatGLM2-6B\web_demo.py", line 66, in predict
    for response, history, past_key_values in model.stream_chat(tokenizer, input, history, past_key_values=past_key_values,       
  File "C:\Users\mzw\.conda\envs\ChatGLM\lib\site-packages\torch\autograd\grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "C:\Users\mzw/.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 1058, in stream_chat
    for outputs in self.stream_generate(**inputs, past_key_values=past_key_values,
  File "C:\Users\mzw\.conda\envs\ChatGLM\lib\site-packages\torch\autograd\grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "C:\Users\mzw/.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 1143, in stream_generate
    outputs = self(
  File "C:\Users\mzw\.conda\envs\ChatGLM\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\mzw/.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 932, in forward  
    transformer_outputs = self.transformer(
  File "C:\Users\mzw\.conda\envs\ChatGLM\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\mzw/.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 828, in forward  
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "C:\Users\mzw\.conda\envs\ChatGLM\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\mzw/.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 638, in forward  
    layer_ret = layer(
  File "C:\Users\mzw\.conda\envs\ChatGLM\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\mzw/.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 542, in forward  
    attention_output, kv_cache = self.self_attention(
  File "C:\Users\mzw\.conda\envs\ChatGLM\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\mzw/.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 374, in forward  
    mixed_x_layer = self.query_key_value(hidden_states)
  File "C:\Users\mzw\.conda\envs\ChatGLM\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\mzw/.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization.py", line 502, in forward      
    output = W8A16Linear.apply(input, self.weight, self.weight_scale, self.weight_bit_width)
  File "C:\Users\mzw/.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization.py", line 75, in forward       
    weight = extract_weight_to_half(quant_w, scale_w, weight_bit_width)
  File "C:\Users\mzw/.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization.py", line 287, in extract_weight_to_half
    func = kernels.int4WeightExtractionHalf
AttributeError: 'NoneType' object has no attribute 'int4WeightExtractionHalf'
