### ISSUE TITLE
[BUG/Help] 已经下载chatglm2-6b模型，但是python web_demo.py抛出路径错误

### ISSUE THREAD

**Issue by mainxx** [THUDM/ChatGLM2-6B#15]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

如果是：
`tokenizer = AutoTokenizer.from_pretrained("chatglm2-6b/", trust_remote_code=True)
model = AutoModel.from_pretrained("chatglm2-6b/", trust_remote_code=True, device='cuda')`
则报错：
`PS C:\Users\joven\source\Github\ChatGLM2-6B-main\ChatGLM2-6B-main> python web_demo.py
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "C:\Users\joven\source\Github\ChatGLM2-6B-main\ChatGLM2-6B-main\web_demo.py", line 5, in <module>
    tokenizer = AutoTokenizer.from_pretrained("chatglm2-6b/", trust_remote_code=True)
  File "C:\Users\joven\miniconda3\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 663, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(
  File "C:\Users\joven\miniconda3\lib\site-packages\transformers\dynamic_module_utils.py", line 399, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "C:\Users\joven\miniconda3\lib\site-packages\transformers\dynamic_module_utils.py", line 157, in get_class_in_module
    shutil.copy(f"{module_dir}/{module_file_name}", tmp_dir)
  File "C:\Users\joven\miniconda3\lib\shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\joven\miniconda3\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\joven\\.cache\\huggingface\\modules\\transformers_modules\\chatglm2-6b/chatglm2-6b/tokenization_chatglm.py'`

反正正反斜杠，全路径，都试过了。求好心人解答。

### Steps To Reproduce

根据文档步骤来的。
chatglm2-6b模型大小：23.2 GB

### Environment

```markdown
- OS:Windows11
- Python:py 3.10.10
- Transformers:4.27.1
- PyTorch:2.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by Nico0416** [comment]
chatglm2-6b这个目录下是 https://huggingface.co/THUDM/chatglm2-6b/tree/main 这个里面的文件了吗

**Comment by mainxx** [comment]
@Nico0416  是的，一模一样，如图1：

但是我chatglm2-6b跟代码同一级。如图2：

图1：
![image](https://github.com/THUDM/ChatGLM2-6B/assets/14832636/a1b1682b-cfeb-4839-bb21-6ccdb8700978)

图2：

![image](https://github.com/THUDM/ChatGLM2-6B/assets/14832636/5ea98147-89a7-44c2-b100-9d5d66b6b892)

**Comment by linzeyang** [comment]
I prefer to use the absolute path of the cloned model repository in `web_demo.py` so that I can run `web_demo.py` wherever I want. In your case you can try passing `C:\Users\joven\source\Github\ChatGLM2-6B-main\ChatGLM2-6B-main\chatglm2-6b\` (or replace `\` with `\\`? I'm not sure how exactly the path show be on Windows) to `AutoTokenizer.from_pretrained()` method.

hope this can help you.

**Comment by xuzhiang** [comment]
This is my code, and it can run on my Windows platform:
tokenizer = AutoTokenizer.from_pretrained("D:\model\chatglm2-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("D:\model\chatglm2-6b", trust_remote_code=True, device='cuda')

**Comment by mainxx** [comment]
@xuzhiang 

Error:
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Traceback (most recent call last):
  File "C:\Users\joven\source\Github\ChatGLM2-6B-main\ChatGLM2-6B-main\web_demo.py", line 6, in <module>
    model = AutoModel.from_pretrained("C:\\Users\\joven\\source\\Github\\ChatGLM2-6B-main\\ChatGLM2-6B-main\\chatglm2-6b\\", trust_remote_code=True, device='cuda')
  File "C:\Users\joven\miniconda3\lib\site-packages\transformers\models\auto\auto_factory.py", line 466, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\joven\miniconda3\lib\site-packages\transformers\modeling_utils.py", line 2498, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "C:\Users\joven/.cache\huggingface\modules\transformers_modules\modeling_chatglm.py", line 767, in __init__
    self.transformer = ChatGLMModel(config, empty_init=empty_init, device=device)
  File "C:\Users\joven/.cache\huggingface\modules\transformers_modules\modeling_chatglm.py", line 690, in __init__
    self.embedding = init_method(Embedding, config, **init_kwargs)
  File "C:\Users\joven\miniconda3\lib\site-packages\torch\nn\utils\init.py", line 52, in skip_init
    return module_cls(*args, **kwargs).to_empty(device=final_device)
  File "C:\Users\joven\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1024, in to_empty
    return self._apply(lambda t: torch.empty_like(t, device=device))
  File "C:\Users\joven\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\joven\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\joven\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1024, in <lambda>
    return self._apply(lambda t: torch.empty_like(t, device=device))
  File "C:\Users\joven\miniconda3\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

是我显卡不支持的问题？4070Ti

**Comment by mainxx** [comment]
tokenizer = AutoTokenizer.from_pretrained("F:\model\chatglm2-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("F:\model\chatglm2-6b", trust_remote_code=True, device='cuda')

This is the same as the mistake above

**Comment by ysyx2008** [comment]
> 

你这是安装了CPU版本的torch吧，去官网装个cuda版本的。

**Comment by ysyx2008** [comment]
<img width="1920" alt="2023-06-26" src="https://github.com/THUDM/ChatGLM2-6B/assets/11251894/ad75221b-d332-47ab-9482-85e74f29d3ce">
2我还没试，但1代这样配置是没有问题的，顺利使用。可以参考下。
win10系统，使用了相对路径。

**Comment by ysyx2008** [comment]
可能就是最后不要加斜杠或是反斜杠？

**Comment by ysyx2008** [comment]
另外，模型没有这么大吧，也就12G左右。

**Comment by mainxx** [comment]
@ysyx2008  好的。我试一试。

**Comment by dogvane** [comment]
感觉是 transformers 的问题，无法本地加载，可以试试下面的代码。

modelFile = 'G:\\GPT\\ChatGLM2-6B\\cache\\chatglm2-6b-int4'
# modelFile ='THUDM/chatglm2-6b'

mf = Path(modelFile)

tokenizer = AutoTokenizer.from_pretrained(mf, trust_remote_code=True)
model = AutoModel.from_pretrained(mf, trust_remote_code=True).half().quantize(4).cuda()

**Comment by mainxx** [comment]
@dogvane 

解决了那个。我是这样解决的：
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
之前用pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118，好像不行。
但是又遇到新问题：
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\Users\joven\miniconda3\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\joven\miniconda3\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "C:\Users\joven\miniconda3\lib\site-packages\gradio\blocks.py", line 1093, in call_function
    prediction = await utils.async_iteration(iterator)
  File "C:\Users\joven\miniconda3\lib\site-packages\gradio\utils.py", line 341, in async_iteration
    return await iterator.__anext__()
  File "C:\Users\joven\miniconda3\lib\site-packages\gradio\utils.py", line 334, in __anext__
    return await anyio.to_thread.run_sync(
  File "C:\Users\joven\miniconda3\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\joven\miniconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\joven\miniconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\joven\miniconda3\lib\site-packages\gradio\utils.py", line 317, in run_sync_iterator_async
    return next(iterator)
  File "C:\Users\joven\source\Github\ChatGLM2-6B-main\ChatGLM2-6B-main\web_demo.py", line 64, in predict
    for response, history, past_key_values in model.stream_chat(tokenizer, input, history, past_key_values=past_key_values,
  File "C:\Users\joven\miniconda3\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\joven/.cache\huggingface\modules\transformers_modules\chatglm2-6b\modeling_chatglm.py", line 973, in stream_chat
    for outputs in self.stream_generate(**inputs, past_key_values=past_key_values,
  File "C:\Users\joven\miniconda3\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\joven/.cache\huggingface\modules\transformers_modules\chatglm2-6b\modeling_chatglm.py", line 1057, in stream_generate
    outputs = self(
  File "C:\Users\joven\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\joven/.cache\huggingface\modules\transformers_modules\chatglm2-6b\modeling_chatglm.py", line 845, in forward
    transformer_outputs = self.transformer(
  File "C:\Users\joven\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\joven/.cache\huggingface\modules\transformers_modules\chatglm2-6b\modeling_chatglm.py", line 741, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "C:\Users\joven\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\joven/.cache\huggingface\modules\transformers_modules\chatglm2-6b\modeling_chatglm.py", line 588, in forward
    hidden_states, kv_cache = layer(
  File "C:\Users\joven\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\joven/.cache\huggingface\modules\transformers_modules\chatglm2-6b\modeling_chatglm.py", line 510, in forward
    attention_output, kv_cache = self.self_attention(
  File "C:\Users\joven\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\joven/.cache\huggingface\modules\transformers_modules\chatglm2-6b\modeling_chatglm.py", line 374, in forward
    query_layer = apply_rotary_pos_emb(query_layer, rotary_pos_emb)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: nvrtc: error: failed to open nvrtc-builtins64_118.dll.
  Make sure that nvrtc-builtins64_118.dll is installed correctly.

**Comment by dogvane** [comment]
要不降一个版本到117再试试

**Comment by msly** [comment]
1 本地绝对路径要使用 \\ 不能用 / , 否则报错OSError: [WinError 123]
2 torch要用gpu版本的, 
`pip uninstall torch`
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117`
3 显存<9G 的下载int4版本 
`git clone https://huggingface.co/THUDM/chatglm2-6b-int4`
10G内存可以用int8量化
`model = AutoModel.from_pretrained("Z:\\chatglm2-6b", trust_remote_code=True).quantize(8).cuda()`

**Comment by jiangbossB** [comment]
绝对路径相对路径 \\，\ ,Path()， 都试过了 不行啊  Win10 cu118 tramsformers 4.27.1 
chatglm6b就不会报错

**Comment by jiangbossB** [comment]
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by wupj1993** [comment]
> 绝对路径相对路径 \，\ ,Path()， 都试过了 不行啊 Win10 cu118 tramsformers 4.27.1 chatglm6b就不会报错

你模型（ https://huggingface.co/THUDM/chatglm2-6b/tree/main ）下面的文件是不是不完整，我之前也是不完整才导致一样的错，

**Comment by jiangbossB** [comment]
> > 绝对路径相对路径 \，\ ,Path()， 都试过了 不行啊 Win10 cu118 tramsformers 4.27.1 chatglm6b就不会报错
> 
> 你模型（ https://huggingface.co/THUDM/chatglm2-6b/tree/main ）下面的文件是不是不完整，我之前也是不完整才导致一样的错，

牛逼  确实文件少了 git lfs不是很懂用  之前都是手动下载的文件  多谢多谢

**Comment by mainxx** [comment]
git lfs下载到一半，能不能继续下载。经常都是下载到一半。

**Comment by jiangbossB** [comment]
> git lfs下载到一半，能不能继续下载。经常都是下载到一半。

是这样的而且不显示进度 我都是直接用浏览器下载了

**Comment by baiyutang** [comment]
我用 `wget`

**Comment by moviewang** [comment]
> tokenizer = AutoTokenizer.from_pretrained("D:\model\chatglm2-6b", trust_remote_code=True) model = AutoModel.from_pretrained("D:\model\chatglm2-6b", trust_remote_code=True, device='cuda')

我的出现这个原因是少下载了tokenizer.model
