### ISSUE TITLE
[BUG/Help] <成功运行，提问后出现错误>

### ISSUE THREAD

**Issue by chinabaijunjie** [THUDM/ChatGLM2-6B#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="1017" alt="image" src="https://github.com/THUDM/ChatGLM2-6B/assets/33617869/98a75ff5-cc04-48b7-b1eb-2db3c07a73a6">
<img width="854" alt="image" src="https://github.com/THUDM/ChatGLM2-6B/assets/33617869/d19c148c-8204-4e0b-8c90-6611374d0bb8">
错误信息：AttributeError: 'ChatGLMTokenizer' object has no attribute 'build_prompt'

在回答我的问题的时候报错了。看起来是缺少了‘build_prompt’的属性吗？

### Steps To Reproduce

1、执行 streamlit run web_demo2.py --server.port 6006，成功运行
2、提问
3、出现了上面的错误信息

### Environment

```markdown
- OS: MacOs 13.4.1（22FB82）
- Python: 3.10.10
- Transformers: 4.30.2
- PyTorch: 
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : false
```

**Comment by duzx16** [comment]
更新一下 `tokenization_chatglm.py`

**Comment by kanseaveg** [comment]
我也存在类似的问题，不过我是在ptuning的时候出现的，并且也更新了tokenization_chatglm.py文件
```shell
master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/home/amax/miniconda3/envs/cyy-glm/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: /home/amax/miniconda3/envs/cyy-glm did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
/home/amax/miniconda3/envs/cyy-glm/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('10809'), PosixPath('http'), PosixPath('//10.21.49.67')}
  warn(msg)
/home/amax/miniconda3/envs/cyy-glm/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/tmp/torchelastic_uenn36cw/e73cb557-e1b1-4204-8e5a-9340e7461e8c_x8to9ij0/attempt_0/0/error.json')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 111
CUDA SETUP: Loading binary /home/amax/miniconda3/envs/cyy-glm/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111.so...
07/07/2023 21:09:56 - WARNING - __main__ - Process rank: 0, device: cuda:0, n_gpu: 1distributed training: True, 16-bits training: False07/07/2023 21:09:56 - INFO - __main__ - Training/evaluation parameters Seq2SeqTrainingArguments(
_n_gpu=1,
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_pin_memory=True,
ddp_backend=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=False,
do_predict=False,
do_train=True,
eval_accumulation_steps=None,
eval_delay=0,
eval_steps=None,
evaluation_strategy=no,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'fsdp_min_num_params': 0, 'xla': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
generation_config=None,
generation_max_length=None,
generation_num_beams=None,
gradient_accumulation_steps=16,
gradient_checkpointing=False,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.02,
length_column_name=length,
load_best_model_at_end=False,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=output/spider-chatglm2-6b-pt-128-2e-2/runs/Jul07_21-09-56_admin.cluster.local,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=10,
logging_strategy=steps,
lr_scheduler_type=linear,
max_grad_norm=1.0,
max_steps=3000,
metric_for_best_model=None,
mp_parameters=,
no_cuda=False,
num_train_epochs=3.0,
optim=adamw_hf,
optim_args=None,
output_dir=output/spider-chatglm2-6b-pt-128-2e-2,
overwrite_output_dir=True,
past_index=-1,
per_device_eval_batch_size=1,
per_device_train_batch_size=1,
predict_with_generate=True,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=['tensorboard'],
resume_from_checkpoint=None,
run_name=output/spider-chatglm2-6b-pt-128-2e-2,
save_on_each_node=False,
save_safetensors=False,
save_steps=1000,
save_strategy=steps,
save_total_limit=None,
seed=42,
sharded_ddp=[],
skip_memory_metrics=True,
sortish_sampler=False,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.0,
warmup_steps=0,
weight_decay=0.0,
xpu_backend=None,
)
07/07/2023 21:09:57 - WARNING - datasets.builder - Found cached dataset json (/home/amax/.cache/huggingface/datasets/json/default-659d5e626290f964/0.0.0/0f7e3662623656454fcd2b650f34e886a7db4b9104504885bd462096cc7a9f51)
100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 913.19it/s][INFO|configuration_utils.py:667] 2023-07-07 21:09:57,853 >> loading configuration file ../../models/chatglm-6b/config.json
[INFO|configuration_utils.py:667] 2023-07-07 21:09:57,855 >> loading configuration file ../../models/chatglm-6b/config.json
[INFO|configuration_utils.py:725] 2023-07-07 21:09:57,855 >> Model config ChatGLMConfig {
  "_name_or_path": "../../models/chatglm-6b",
  "architectures": [
    "ChatGLMModel"
  ],
  "auto_map": {
    "AutoConfig": "configuration_chatglm.ChatGLMConfig",
    "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration"
  },
  "bos_token_id": 130004,
  "eos_token_id": 130005,
  "gmask_token_id": 130001,
  "hidden_size": 4096,
  "inner_hidden_size": 16384,
  "layernorm_epsilon": 1e-05,
  "mask_token_id": 130000,
  "max_sequence_length": 2048,
  "model_type": "chatglm",
  "num_attention_heads": 32,
  "num_layers": 28,
  "pad_token_id": 3,
  "position_encoding_2d": true,
  "pre_seq_len": null,
  "prefix_projection": false,
  "quantization_bit": 0,
  "torch_dtype": "float16",
  "transformers_version": "4.30.2",
  "use_cache": true,
  "vocab_size": 130528
}

[INFO|tokenization_utils_base.py:1821] 2023-07-07 21:09:57,858 >> loading file ice_text.model
[INFO|tokenization_utils_base.py:1821] 2023-07-07 21:09:57,858 >> loading file added_tokens.json
[INFO|tokenization_utils_base.py:1821] 2023-07-07 21:09:57,858 >> loading file special_tokens_map.json
[INFO|tokenization_utils_base.py:1821] 2023-07-07 21:09:57,858 >> loading file tokenizer_config.json
[INFO|modeling_utils.py:2575] 2023-07-07 21:09:58,210 >> loading weights file ../../models/chatglm-6b/pytorch_model.bin.index.json
[INFO|configuration_utils.py:577] 2023-07-07 21:09:58,211 >> Generate config GenerationConfig {
  "_from_model_config": true,
  "bos_token_id": 130004,
  "eos_token_id": 130005,
  "pad_token_id": 3,
  "transformers_version": "4.30.2"
}

Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████| 8/8 [00:10<00:00,  1.31s/it][INFO|modeling_utils.py:3295] 2023-07-07 21:10:09,070 >> All model checkpoint weights were used when initializing ChatGLMForConditionalGeneration.

[WARNING|modeling_utils.py:3297] 2023-07-07 21:10:09,070 >> Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at ../../models/chatglm-6b and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[INFO|modeling_utils.py:2927] 2023-07-07 21:10:09,072 >> Generation config file not found, using a generation config created from the model config.
RemoteTraceback:                                                                                                                       
"""
Traceback (most recent call last):
  File "/home/amax/miniconda3/envs/cyy-glm/lib/python3.10/site-packages/multiprocess/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/amax/miniconda3/envs/cyy-glm/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 1349, in 
_write_generator_to_queue
    for i, result in enumerate(func(**kwargs)):
  File "/home/amax/miniconda3/envs/cyy-glm/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3329, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "/home/amax/miniconda3/envs/cyy-glm/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 3210, in 
apply_function_on_filtered_inputs
    processed_inputs = function(*fn_args, *additional_args, **fn_kwargs)
  File "/home/amax/euan/code/llm/chatglm2-6b/ptuning/main.py", line 192, in preprocess_function_train
    prompt = tokenizer.build_prompt(query, history)
AttributeError: 'ChatGLMTokenizer' object has no attribute 'build_prompt'
"""

The above exception was the direct cause of the following exception:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/amax/euan/code/llm/chatglm2-6b/ptuning/main.py:411 in <module>                             │
│                                                                                                  │
│   408                                                                                            │
│   409                                                                                            │
│   410 if __name__ == "__main__":                                                                 │
│ ❱ 411 │   main()                                                                                 │
│   412                                                                                            │
│                                                                                                  │
│ /home/amax/euan/code/llm/chatglm2-6b/ptuning/main.py:229 in main                                 │
│                                                                                                  │
│   226 │   │   │   max_train_samples = min(len(train_dataset), data_args.max_train_samples)       │
│   227 │   │   │   train_dataset = train_dataset.select(range(max_train_samples))                 │
│   228 │   │   with training_args.main_process_first(desc="train dataset map pre-processing"):    │
│ ❱ 229 │   │   │   train_dataset = train_dataset.map(                                             │
│   230 │   │   │   │   preprocess_function_train,                                                 │
│   231 │   │   │   │   batched=True,                                                              │
│   232 │   │   │   │   num_proc=data_args.preprocessing_num_workers,                              │
│                                                                                                  │
│ /home/amax/miniconda3/envs/cyy-glm/lib/python3.10/site-packages/datasets/arrow_dataset.py:563 in │
│ wrapper                                                                                          │
│                                                                                                  │
│    560 │   │   else:                                                                             │
│    561 │   │   │   self: "Dataset" = kwargs.pop("self")                                          │
│    562 │   │   # apply actual function                                                           │
│ ❱  563 │   │   out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)                │
│    564 │   │   datasets: List["Dataset"] = list(out.values()) if isinstance(out, dict) else [ou  │
│    565 │   │   for dataset in datasets:                                                          │
│    566 │   │   │   # Remove task templates if a column mapping of the template is no longer val  │
│                                                                                                  │
│ /home/amax/miniconda3/envs/cyy-glm/lib/python3.10/site-packages/datasets/arrow_dataset.py:528 in │
│ wrapper                                                                                          │
│                                                                                                  │
│    525 │   │   │   "output_all_columns": self._output_all_columns,                               │
│    526 │   │   }                                                                                 │
│    527 │   │   # apply actual function                                                           │
│ ❱  528 │   │   out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)                │
│    529 │   │   datasets: List["Dataset"] = list(out.values()) if isinstance(out, dict) else [ou  │
│    530 │   │   # re-apply format to the output                                                   │
│    531 │   │   for dataset in datasets:                                                          │
│                                                                                                  │
│ /home/amax/miniconda3/envs/cyy-glm/lib/python3.10/site-packages/datasets/arrow_dataset.py:3046   │
│ in map                                                                                           │
│                                                                                                  │
│   3043 │   │   │   │   │   │   leave=False,                                                      │
│   3044 │   │   │   │   │   │   desc=(desc or "Map") + f" (num_proc={num_proc})",                 │
│   3045 │   │   │   │   │   ) as pbar:                                                            │
│ ❱ 3046 │   │   │   │   │   │   for rank, done, content in iflatmap_unordered(                    │
│   3047 │   │   │   │   │   │   │   pool, Dataset._map_single, kwargs_iterable=kwargs_per_job     │
│   3048 │   │   │   │   │   │   ):                                                                │
│   3049 │   │   │   │   │   │   │   if done:                                                      │
│                                                                                                  │
│ /home/amax/miniconda3/envs/cyy-glm/lib/python3.10/site-packages/datasets/utils/py_utils.py:1373  │
│ in iflatmap_unordered                                                                            │
│                                                                                                  │
│   1370 │   │   │   │   if all(async_result.ready() for async_result in async_results) and queue  │
│   1371 │   │   │   │   │   break                                                                 │
│   1372 │   │   # we get the result in case there's an error to raise                             │
│ ❱ 1373 │   │   [async_result.get() for async_result in async_results]                            │
│   1374                                                                                           │
│                                                                                                  │
│ /home/amax/miniconda3/envs/cyy-glm/lib/python3.10/site-packages/datasets/utils/py_utils.py:1373  │
│ in <listcomp>                                                                                    │
│                                                                                                  │
│   1370 │   │   │   │   if all(async_result.ready() for async_result in async_results) and queue  │
│   1371 │   │   │   │   │   break                                                                 │
│   1372 │   │   # we get the result in case there's an error to raise                             │
│ ❱ 1373 │   │   [async_result.get() for async_result in async_results]                            │
│   1374                                                                                           │
│                                                                                                  │
│ /home/amax/miniconda3/envs/cyy-glm/lib/python3.10/site-packages/multiprocess/pool.py:774 in get  │
│                                                                                                  │
│   771 │   │   if self._success:                                                                  │
│   772 │   │   │   return self._value                                                             │
│   773 │   │   else:                                                                              │
│ ❱ 774 │   │   │   raise self._value                                                              │
│   775 │                                                                                          │
│   776 │   def _set(self, i, obj):                                                                │
│   777 │   │   self._success, self._value = obj                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'ChatGLMTokenizer' object has no attribute 'build_prompt'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 35080) of binary: /home/amax/miniconda3/envs/cyy-glm/bin/python
Traceback (most recent call last):
  File "/home/amax/miniconda3/envs/cyy-glm/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/amax/miniconda3/envs/cyy-glm/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/amax/miniconda3/envs/cyy-glm/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/amax/miniconda3/envs/cyy-glm/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/amax/miniconda3/envs/cyy-glm/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/amax/miniconda3/envs/cyy-glm/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-07_21:10:18
  host      : admin.cluster.local
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 35080)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
````

**Comment by kanseaveg** [comment]
已经更新了modeling_chatglm.py和tokenization_chatglm.py这两个大文件，还是不行

**Comment by onetwo12cn** [comment]
> okenization_chatglm.

同问，在微调训练的时候报错

**Comment by kanseaveg** [comment]
我使用原生方式下载预训练模型，现在ptuing没什么问题了，应该不只是这两份文件的问题，应该是文件完整性导致的，huggingface skip large file会导致一些文件没有被完全下载下来。

**Comment by onetwo12cn** [comment]
> > okenization_chatglm.
> 
> 同问，在微调训练的时候报错

我从新下载模型文件，后面运行就可以了

**Comment by kanseaveg** [comment]
说到底还是网络问题【疯狂暗示】

> > > okenization_chatglm.
> > 
> > 
> > 同问，在微调训练的时候报错
> 
> 我从新下载模型文件，后面运行就可以了

**Comment by Ziffer-byakuya** [comment]
> 我使用原生方式下载预训练模型，现在ptuing没什么问题了，应该不只是这两份文件的问题，应该是文件完整性导致的，huggingface skip large file会导致一些文件没有被完全下载下来。

请问重新下载模型文件指的是重新下载chatglm2-6b或者chatglm2-6b-int4文件（就是包含了权重的那个）吗？

**Comment by Amoiensis** [comment]
可以把 /chatglm2-6b 里 tokenization_chatglm.py ，类'ChatGLMTokenizer'的 函数 'build_prompt'，添加到 /chatglm-6b 的tokenization_chatglm.py 里就可以解决该问题了。
