### ISSUE TITLE
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

### ISSUE THREAD

**Issue by ruru023** [THUDM/ChatGLM2-6B#168]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

仓库最简单的案例，用拯救者跑(有点low了?)加载到80%左右失败了。
提示如下，搜了下解决方案，是CPU不支持FP 16,要把model.half()改为model.float()。但不太清楚修改哪里(源码好多地方都涉及)。还是说压根就跑不了~
G:\glm\ChatGLM2-6B\venv\Scripts\python.exe G:\glm\ChatGLM2-6B\demo1.py 
Loading checkpoint shards: 100%|██████████| 7/7 [02:01<00:00, 17.31s/it]
Traceback (most recent call last):
  File "G:\glm\ChatGLM2-6B\demo1.py", line 13, in <module>
    response, history = model.chat(tokenizer, "你好", history=[])
  File "G:\glm\ChatGLM2-6B\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\sqqdc/.cache\huggingface\modules\transformers_modules\data\modeling_chatglm.py", line 1027, in chat
    outputs = self.generate(**inputs, **gen_kwargs)
  File "G:\glm\ChatGLM2-6B\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "G:\glm\ChatGLM2-6B\venv\lib\site-packages\transformers\generation\utils.py", line 1572, in generate
    return self.sample(
  File "G:\glm\ChatGLM2-6B\venv\lib\site-packages\transformers\generation\utils.py", line 2619, in sample
    outputs = self(
  File "G:\glm\ChatGLM2-6B\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\sqqdc/.cache\huggingface\modules\transformers_modules\data\modeling_chatglm.py", line 931, in forward
    transformer_outputs = self.transformer(
  File "G:\glm\ChatGLM2-6B\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\sqqdc/.cache\huggingface\modules\transformers_modules\data\modeling_chatglm.py", line 827, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "G:\glm\ChatGLM2-6B\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\sqqdc/.cache\huggingface\modules\transformers_modules\data\modeling_chatglm.py", line 637, in forward
    layer_ret = layer(
  File "G:\glm\ChatGLM2-6B\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\sqqdc/.cache\huggingface\modules\transformers_modules\data\modeling_chatglm.py", line 541, in forward
    attention_output, kv_cache = self.self_attention(
  File "G:\glm\ChatGLM2-6B\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\sqqdc/.cache\huggingface\modules\transformers_modules\data\modeling_chatglm.py", line 373, in forward
    mixed_x_layer = self.query_key_value(hidden_states)
  File "G:\glm\ChatGLM2-6B\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\glm\ChatGLM2-6B\venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

Process finished with exit code 1

### Expected Behavior

运行成功

### Steps To Reproduce

1. 运行代码如下
2. model = AutoModel.from_pretrained(r"d:\glm", trust_remote_code=True) 去掉了CUDA

### Environment

```markdown
- OS:win11
- Python: 3.10
```

### Anything else?

from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained(r"d:\glm", trust_remote_code=True)
model = AutoModel.from_pretrained(r"d:\glm", trust_remote_code=True) #去掉了 , device='cuda'
model = model.eval()
response, history = model.chat(tokenizer, "你好", history=[])
print(response)

**Comment by duzx16** [comment]
https://github.com/THUDM/ChatGLM2-6B#cpu-%E9%83%A8%E7%BD%B2
