### ISSUE TITLE
[BUG/Help] <title> ptuning 出现 AttributeError: 'Seq2SeqTrainer' object has no attribute 'is_deepspeed_enabled' 错误

### ISSUE THREAD

**Issue by rujews** [THUDM/ChatGLM2-6B#186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

使用ptuning微调，在运行bash train.sh的时候，出现如下错误：
```
Traceback (most recent call last):
  File "/home/xia/github/ChatGLM2-6B/ptuning/main.py", line 411, in <module>
    main()
  File "/home/xia/github/ChatGLM2-6B/ptuning/main.py", line 350, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/xia/github/ChatGLM2-6B/ptuning/trainer.py", line 1635, in train
    return inner_training_loop(
  File "/home/xia/github/ChatGLM2-6B/ptuning/trainer.py", line 1981, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/home/xia/github/ChatGLM2-6B/ptuning/trainer.py", line 2220, in _maybe_log_save_evaluate
    logs["learning_rate"] = self._get_learning_rate()
  File "/home/xia/miniconda3/envs/chatglm/lib/python3.10/site-packages/transformers/trainer_pt_utils.py", line 841, in _get_learning_rate
    if self.is_deepspeed_enabled:
AttributeError: 'Seq2SeqTrainer' object has no attribute 'is_deepspeed_enabled'
```

### Steps To Reproduce

bash train.sh即可复现，猜测和transformers版本有关，ChatGLM的版本没这个问题。

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by rujews** [comment]
#175
