### ISSUE TITLE
[BUG/Help] <title> ptuning 单机多卡问题

### ISSUE THREAD

**Issue by zoey-zy998** [THUDM/ChatGLM2-6B#199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

用自己的数据跑ptuning微调 ChatGLM2-6B/ptuning# sh train.sh ，发现单机多卡的问题
![31dbd098aa7654c5a70158f012ac549](https://github.com/THUDM/ChatGLM2-6B/assets/55828495/8adc4a34-d233-4bba-ac1c-b8df7d52314c)

### Expected Behavior

希望能解决一下这个bug

### Steps To Reproduce

PRE_SEQ_LEN=128
LR=2e-2
NUM_GPUS=1

torchrun --standalone --nnodes=1 --nproc-per-node=$NUM_GPUS main.py \
    --do_train \
    --train_file  /mnt/Algorithm/ChatGLM2-6B/ChatGLM2-Efficient-Tuning/data/train.json\
    --validation_file  /mnt/Algorithm/ChatGLM2-6B/ChatGLM2-Efficient-Tuning/data/train.json\
    --preprocessing_num_workers 10 \
    --prompt_column content \
    --response_column summary \
    --overwrite_cache \
    --model_name_or_path /mnt/Algorithm/ChatGLM2-6B/chatglm2-6b  \
    --output_dir output/chatglm2-6b-pt-$PRE_SEQ_LEN-$LR \
    --overwrite_output_dir \
    --max_source_length 64 \
    --max_target_length 128 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --predict_with_generate \
    --max_steps 1000 \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate $LR \
    --pre_seq_len $PRE_SEQ_LEN \
   #--quantization_bit 4 

### Environment

```markdown
- OS:
- Python:3.8
- Transformers: 4.30.2
- PyTorch:2.0.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by zoey-zy998** [comment]
master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
[2023-07-05 14:29:44,365] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[W socket.cpp:601] [c10d] The client socket has failed to connect to [iZuf6ecr9qv7cnmhk33jk7Z]:43393 (errno: 110 - Connection timed out).
[W socket.cpp:601] [c10d] The client socket has failed to connect to iZuf6ecr9qv7cnmhk33jk7Z:43393 (errno: 110 - Connection timed out).
[E socket.cpp:657] [c10d] The client socket has failed to connect to any network address of (iZuf6ecr9qv7cnmhk33jk7Z, 43393).
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /mnt/Algorithm/ChatGLM2-6B/ptuning/main.py:411 in <module>                                       │
│                                                                                                  │
│   408                                                                                            │
│   409                                                                                            │
│   410 if __name__ == "__main__":                                                                 │
│ ❱ 411 │   main()                                                                                 │
│   412                                                                                            │
│                                                                                                  │
│ /mnt/Algorithm/ChatGLM2-6B/ptuning/main.py:56 in main                                            │
│                                                                                                  │
│    53 │   │   # let's parse it to get our arguments.                                             │
│    54 │   │   model_args, data_args, training_args = parser.parse_json_file(json_file=os.path.   │
│    55 │   else:                                                                                  │
│ ❱  56 │   │   model_args, data_args, training_args = parser.parse_args_into_dataclasses()        │
│    57 │                                                                                          │
│    58 │   # Setup logging                                                                        │
│    59 │   logging.basicConfig(                                                                   │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/transformers/hf_argparser.py:346 in                       │
│ parse_args_into_dataclasses                                                                      │
│                                                                                                  │
│   343 │   │   │   inputs = {k: v for k, v in vars(namespace).items() if k in keys}               │
│   344 │   │   │   for k in keys:                                                                 │
│   345 │   │   │   │   delattr(namespace, k)                                                      │
│ ❱ 346 │   │   │   obj = dtype(**inputs)                                                          │
│   347 │   │   │   outputs.append(obj)                                                            │
│   348 │   │   if len(namespace.__dict__) > 0:                                                    │
│   349 │   │   │   # additional namespace.                                                        │
│ in __init__:115                                                                                  │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/transformers/training_args.py:1340 in __post_init__       │
│                                                                                                  │
│   1337 │   │   if (                                                                              │
│   1338 │   │   │   self.framework == "pt"                                                        │
│   1339 │   │   │   and is_torch_available()                                                      │
│ ❱ 1340 │   │   │   and (self.device.type != "cuda")                                              │
│   1341 │   │   │   and (get_xla_device_type(self.device) != "GPU")                               │
│   1342 │   │   │   and (self.fp16 or self.fp16_full_eval)                                        │
│   1343 │   │   ):                                                                                │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/transformers/training_args.py:1764 in device              │
│                                                                                                  │
│   1761 │   │   The device used by this process.                                                  │
│   1762 │   │   """                                                                               │
│   1763 │   │   requires_backends(self, ["torch"])                                                │
│ ❱ 1764 │   │   return self._setup_devices                                                        │
│   1765 │                                                                                         │
│   1766 │   @property                                                                             │
│   1767 │   def n_gpu(self):                                                                      │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/transformers/utils/generic.py:54 in __get__               │
│                                                                                                  │
│    51 │   │   attr = "__cached_" + self.fget.__name__                                            │
│    52 │   │   cached = getattr(obj, attr, None)                                                  │
│    53 │   │   if cached is None:                                                                 │
│ ❱  54 │   │   │   cached = self.fget(obj)                                                        │
│    55 │   │   │   setattr(obj, attr, cached)                                                     │
│    56 │   │   return cached                                                                      │
│    57                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/transformers/training_args.py:1695 in _setup_devices      │
│                                                                                                  │
│   1692 │   │   │   del os.environ["ACCELERATE_USE_DEEPSPEED"]                                    │
│   1693 │   │   │   self._n_gpu = 1                                                               │
│   1694 │   │   else:                                                                             │
│ ❱ 1695 │   │   │   self.distributed_state = PartialState(backend=self.ddp_backend)               │
│   1696 │   │   │   self._n_gpu = 1                                                               │
│   1697 │   │   if not is_sagemaker_mp_enabled():                                                 │
│   1698 │   │   │   device = self.distributed_state.device                                        │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/accelerate/state.py:191 in __init__                       │
│                                                                                                  │
│   188 │   │   │   │   │   # Special case for `TrainingArguments`, where `backend` will be `Non   │
│   189 │   │   │   │   │   if self.backend is None:                                               │
│   190 │   │   │   │   │   │   self.backend = "nccl"                                              │
│ ❱ 191 │   │   │   │   │   torch.distributed.init_process_group(backend=self.backend, **kwargs)   │
│   192 │   │   │   │   self.num_processes = torch.distributed.get_world_size()                    │
│   193 │   │   │   │   self.process_index = torch.distributed.get_rank()                          │
│   194 │   │   │   │   self.local_process_index = int(os.environ.get("LOCAL_RANK", -1))           │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py:900 in              │
│ init_process_group                                                                               │
│                                                                                                  │
│    897 │   │   │   rendezvous_iterator = rendezvous(                                             │
│    898 │   │   │   │   init_method, rank, world_size, timeout=timeout                            │
│    899 │   │   │   )                                                                             │
│ ❱  900 │   │   │   store, rank, world_size = next(rendezvous_iterator)                           │
│    901 │   │   │   store.set_timeout(timeout)                                                    │
│    902 │   │   │                                                                                 │
│    903 │   │   │   # Use a PrefixStore to avoid accidental overrides of keys used by             │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/torch/distributed/rendezvous.py:245 in                    │
│ _env_rendezvous_handler                                                                          │
│                                                                                                  │
│   242 │   master_addr = _get_env_or_raise("MASTER_ADDR")                                         │
│   243 │   master_port = int(_get_env_or_raise("MASTER_PORT"))                                    │
│   244 │                                                                                          │
│ ❱ 245 │   store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)        │
│   246 │                                                                                          │
│   247 │   yield (store, rank, world_size)                                                        │
│   248                                                                                            │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/torch/distributed/rendezvous.py:176 in _create_c10d_store │
│                                                                                                  │
│   173 │   │   return PrefixStore(f"/worker/attempt_{attempt}", tcp_store)                        │
│   174 │   else:                                                                                  │
│   175 │   │   start_daemon = rank == 0                                                           │
│ ❱ 176 │   │   return TCPStore(                                                                   │
│   177 │   │   │   hostname, port, world_size, start_daemon, timeout, multi_tenant=True           │
│   178 │   │   )                                                                                  │
│   179                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: The client socket has failed to connect to any network address of (iZuf6ecr9qv7cnmhk33jk7Z, 43393). The client socket has
failed to connect to iZuf6ecr9qv7cnmhk33jk7Z:43393 (errno: 110 - Connection timed out).
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2126) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-05_14:34:07
  host      : iZuf6ecr9qv7cnmhk33jk7Z
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2126)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by duzx16** [comment]
服务器上是否有防火墙？

**Comment by lvbin0827** [comment]
解决了吗？我也一直报这错误，transformers试了好几个版本了

**Comment by Skysliao** [comment]
解决了吗？我也一直报这错误

**Comment by Skysliao** [comment]
> 解决了吗？我也一直报这错误

我是 单机单卡
