### ISSUE TITLE
[BUG/Help] <运行openai_api.py时出现TypeError: issubclass() arg 1 must be a class>

### ISSUE THREAD

**Issue by shopflyer-df** [THUDM/ChatGLM2-6B#201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

正常部署配置以后，在进行openai_api部署的时候报错，其他的，例如api，cli，web_demo 1 web_demo 2 甚至自己写已个python去调用都没有问题，只有openai_api会有这个问题。
具体报错信息：
Traceback (most recent call last):
  File "openai_api.py", line 52, in <module>
    class ChatMessage(BaseModel):
  File "pydantic/main.py", line 204, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 488, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 419, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 534, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 638, in pydantic.fields.ModelField._type_analysis
  File "/usr/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
不知道这个问题的原因是什么，希望有没有比较专业的人士能点拨一下

### Steps To Reproduce

按照文档中的进行配置，并且只改动了CHECKPOINT，用本地模型加载，其他的几个api，cli之类的都是这样加载的，没有问题
CHECKPOINT_PATH = "/ChatGLM2-6B/models/chatglm2-6b"
if __name__ == "__main__":
    tokenizer = AutoTokenizer.from_pretrained(CHECKPOINT_PATH, trust_remote_code=True)
    model = AutoModel.from_pretrained(CHECKPOINT_PATH, trust_remote_code=True).cuda()

    model.eval()
    uvicorn.run(app, host='0.0.0.0', port=8501, workers=1)

### Environment

```markdown
- OS:Ubuntu 20.04
- Python:3.8.10
- Transformers:4.30.2
- PyTorch:2.0.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by duzx16** [comment]
可能跟 pydantic 的版本有关，可以安装 1.10.2 版本试一下

**Comment by ScrapperEthan** [comment]
升级一下pydantic 的版本
