### ISSUE TITLE
[BUG/Help] 成功运行demo，但返回的都是无意义文字

### ISSUE THREAD

**Issue by lbzerol** [THUDM/ChatGLM2-6B#280]
<img width="929" alt="image" src="https://github.com/THUDM/ChatGLM2-6B/assets/6376117/a4bb0ec7-9d97-411a-8886-29751a43ee82">

有一些错误提示，但是忽略后程序是正常运行的
<img width="1417" alt="image" src="https://github.com/THUDM/ChatGLM2-6B/assets/6376117/63828e20-3d62-4a94-b6da-c7c1a04905ec">
<img width="1401" alt="image" src="https://github.com/THUDM/ChatGLM2-6B/assets/6376117/9098852f-bf83-49fa-9a93-026e117c76b9">

环境是M1pro 16G内存的MBP
demo调用使用chatglm2-6b-int4 ，调用参数如下

<img width="1103" alt="image" src="https://github.com/THUDM/ChatGLM2-6B/assets/6376117/86c481c7-d1ff-41ad-8d13-bebbf5bb422d">

### Environment

```markdown
- OS:MacOS 13.4
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :

```

**Comment by lbzerol** [comment]
同时试了chatglm-6b-int4和chatglm2-6b-int4  似乎是同样的现象

**Comment by nlp999** [comment]
chatglm2-6b模型里有个文件config.json，里面有个参数"use_cache": true,你看下是不是改成了false？

**Comment by bugxzhu** [comment]
我的也是，出现乱七八糟的回复，后面出现错误
Traceback (most recent call last):
  File "/data/ChatGLM2-6B/venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/data/ChatGLM2-6B/web_demo2.py", line 62, in <module>
    for response, history, past_key_values in model.stream_chat(tokenizer, prompt_text, history,
  File "/data/ChatGLM2-6B/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 56, in generator_context
    response = gen.send(request)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py", line 1063, in stream_chat
    response = tokenizer.decode(outputs)
  File "/data/ChatGLM2-6B/venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3509, in decode
    return self._decode(
  File "/data/ChatGLM2-6B/venv/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 931, in _decode
    filtered_tokens = self.convert_ids_to_tokens(token_ids, skip_special_tokens=skip_special_tokens)
  File "/data/ChatGLM2-6B/venv/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 912, in convert_ids_to_tokens
    tokens.append(self._convert_id_to_token(index))
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b/tokenization_chatglm.py", line 121, in _convert_id_to_token
    return self.tokenizer.convert_id_to_token(index)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b/tokenization_chatglm.py", line 60, in convert_id_to_token
    return self.sp_model.IdToPiece(index)
  File "/data/ChatGLM2-6B/venv/lib/python3.10/site-packages/sentencepiece/__init__.py", line 1045, in _batched_func
    return _func(self, arg)
  File "/data/ChatGLM2-6B/venv/lib/python3.10/site-packages/sentencepiece/__init__.py", line 1038, in _func
    raise IndexError('piece id is out of range.')
IndexError: piece id is out of range.

**Comment by lbzerol** [comment]
> chatglm2-6b模型里有个文件config.json，里面有个参数"use_cache": true,你看下是不是改成了false？

感谢关注。。但原始的配置我都没有动过。 clone的是对应chatglm2-6b-int4的仓库 手动下载的bin文件。
不过提供了个思路，我再检查一下文件里的其它配置看看有什么线索
