### ISSUE TITLE
Help：加载本地模型文件报错

### ISSUE THREAD

**Issue by 471417367** [THUDM/ChatGLM2-6B#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

tokenizer = AutoTokenizer.from_pretrained("model/chatglm2-6b", trust_remote_code=True)

python .\web_demo.py
Traceback (most recent call last):
  File ".\web_demo.py", line 6, in <module>
    tokenizer = AutoTokenizer.from_pretrained("model/chatglm2-6b", trust_remote_code=True)
  File "C:\software\Anaconda3\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 676, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
  File "C:\software\Anaconda3\lib\site-packages\transformers\dynamic_module_utils.py", line 443, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "C:\software\Anaconda3\lib\site-packages\transformers\dynamic_module_utils.py", line 164, in get_class_in_module
    module = importlib.import_module(module_path)
  File "C:\software\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked

ModuleNotFoundError: No module named 'transformers_modules.model/chatglm2-6b'
为什么代码中要让transformers_modules去调用本地模型文件夹名称呢

### Steps To Reproduce

transformers==4.30.2

### Environment

```markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by toby911** [comment]
model_path改为绝对路径

**Comment by SethDong** [comment]
截至目前 2023.08.24 降级可以解决
transformers==4.26.1

**Comment by SethDong** [comment]
> 截至目前 2023.08.24 降级可以解决 transformers==4.26.1

降级后会遇到一些奇怪的问题，比如 输出包含nan的张量，最后吧transformers更新到了最新的4.32.0

**Comment by 471417367** [comment]
路径改为"model\\chatglm2-6b"就可以了
