### ISSUE TITLE
[BUG/Help] 返回报错not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by dengyang0818** [THUDM/ChatGLM2-6B#297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "E:\anaconda3\envs\ChatGLM2-6B\lib\site-packages\gradio\routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\anaconda3\envs\ChatGLM2-6B\lib\site-packages\gradio\blocks.py", line 1384, in process_api
    result = await self.call_function(
  File "E:\anaconda3\envs\ChatGLM2-6B\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await utils.async_iteration(iterator)
  File "E:\anaconda3\envs\ChatGLM2-6B\lib\site-packages\gradio\utils.py", line 343, in async_iteration
    return await iterator.__anext__()
  File "E:\anaconda3\envs\ChatGLM2-6B\lib\site-packages\gradio\utils.py", line 336, in __anext__
    return await anyio.to_thread.run_sync(
  File "E:\anaconda3\envs\ChatGLM2-6B\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\anaconda3\envs\ChatGLM2-6B\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\anaconda3\envs\ChatGLM2-6B\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\anaconda3\envs\ChatGLM2-6B\lib\site-packages\gradio\utils.py", line 319, in run_sync_iterator_async
    return next(iterator)
  File "E:\anaconda3\envs\ChatGLM2-6B\lib\site-packages\gradio\utils.py", line 688, in gen_wrapper
    yield from f(*args, **kwargs)
  File "E:\workspace\ChatGLM2-6B\web_demo.py", line 68, in predict
    for response, history, past_key_values in model.stream_chat(tokenizer, input, history, past_key_values=past_key_values,
ValueError: not enough values to unpack (expected 3, got 2)

### Steps To Reproduce

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "E:\anaconda3\envs\ChatGLM2-6B\lib\site-packages\gradio\routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\anaconda3\envs\ChatGLM2-6B\lib\site-packages\gradio\blocks.py", line 1384, in process_api
    result = await self.call_function(
  File "E:\anaconda3\envs\ChatGLM2-6B\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await utils.async_iteration(iterator)
  File "E:\anaconda3\envs\ChatGLM2-6B\lib\site-packages\gradio\utils.py", line 343, in async_iteration
    return await iterator.__anext__()
  File "E:\anaconda3\envs\ChatGLM2-6B\lib\site-packages\gradio\utils.py", line 336, in __anext__
    return await anyio.to_thread.run_sync(
  File "E:\anaconda3\envs\ChatGLM2-6B\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\anaconda3\envs\ChatGLM2-6B\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\anaconda3\envs\ChatGLM2-6B\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\anaconda3\envs\ChatGLM2-6B\lib\site-packages\gradio\utils.py", line 319, in run_sync_iterator_async
    return next(iterator)
  File "E:\anaconda3\envs\ChatGLM2-6B\lib\site-packages\gradio\utils.py", line 688, in gen_wrapper
    yield from f(*args, **kwargs)
  File "E:\workspace\ChatGLM2-6B\web_demo.py", line 68, in predict
    for response, history, past_key_values in model.stream_chat(tokenizer, input, history, past_key_values=past_key_values,
ValueError: not enough values to unpack (expected 3, got 2)

### Environment

```markdown
- OS:Windows 11 pro
- Python:3.10.12
- Transformers:4.30.2
- PyTorch:2.0.1+cu118
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :true
```

**Comment by lilongxian** [comment]
这是由于你在调用stream_chat函数时，参数return_past_key_values没有设为True

**Comment by fndxpg** [comment]
说了和没说一样

**Comment by TzyTman** [comment]
同问

**Comment by Yinke1121** [comment]
实测把web_demo.py 或 web_demo2.py 中最后的代码
 for response, history, past_key_value in model.stream_chat(tokenizer, prompt_text, history,
                                                                past_key_values=past_key_values,
                                                                max_length=max_length, top_p=top_p,
                                                                temperature=temperature,
                                                                return_past_key_values=True):
                                                                
改成
for response, history in model.stream_chat(tokenizer, prompt_text, history,
                                                                past_key_values=past_key_values,
                                                                max_length=max_length, top_p=top_p,
                                                                temperature=temperature,
                                                                return_past_key_values=True):
 就好了（也就是把第一行中的past_key_value去掉），但不知道会有什么影响
