### ISSUE TITLE
[BUG/Help] openai_api.py脚步运行报错

### ISSUE THREAD

**Issue by dengliming** [THUDM/ChatGLM2-6B#308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

INFO:     Started server process [299011]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8502 (Press CTRL+C to quit)
INFO:     172.17.0.2:40642 - "GET /v1/models?path=v1&path=models HTTP/1.1" 200 OK
INFO:     172.17.0.2:40642 - "POST /v1/chat/completions?path=v1&path=chat&path=completions HTTP/1.1" 200 OK
/data/ChatGLM2-6B/openai_api.py:138: PydanticDeprecatedSince20: The `json` method is deprecated; use `model_dump_json` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.0.2/migration/
  yield "{}".format(chunk.json(exclude_unset=True, ensure_ascii=False))
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3/lib/python3.11/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/python3/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/python3/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/python3/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/python3/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/python3/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/python3/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/python3/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/python3/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/python3/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/python3/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/python3/lib/python3.11/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/usr/local/python3/lib/python3.11/site-packages/sse_starlette/sse.py", line 237, in __call__
    async with anyio.create_task_group() as task_group:
  File "/usr/local/python3/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/usr/local/python3/lib/python3.11/site-packages/sse_starlette/sse.py", line 240, in wrap
    await func()
  File "/usr/local/python3/lib/python3.11/site-packages/sse_starlette/sse.py", line 225, in stream_response
    async for data in self.body_iterator:
  File "/data/ChatGLM2-6B/openai_api.py", line 138, in predict
    yield "{}".format(chunk.json(exclude_unset=True, ensure_ascii=False))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3/lib/python3.11/site-packages/typing_extensions.py", line 2562, in wrapper
    return __arg(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3/lib/python3.11/site-packages/pydantic/main.py", line 926, in json
    raise TypeError('`dumps_kwargs` keyword arguments are no longer supported.')
TypeError: `dumps_kwargs` keyword arguments are no longer supported.

### Expected Behavior

无异常

### Steps To Reproduce

python openai_api.py
然后[ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web/tree/main) 配置BaseURL使用

### Environment

```markdown
- OS: Linux VM-16-10-tencentos 5.4.119-19-0009.11
- Python: 3.11.3
- Transformers:
- PyTorch: 2.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by dengliming** [comment]
pydantic库从版本1.8.0开始不再支持dumps_kwargs关键字参数。chunk.json()方法使用了exclude_unset=True和ensure_ascii=False这两个关键字参数。

`yield "{}".format(chunk.json(exclude_unset=True, ensure_ascii=False))`

换成
```
import json
yield json.dumps(chunk.dict(exclude_unset=True), ensure_ascii=False)
```

**Comment by ayakasuki** [comment]
ok 换掉就好了

**Comment by valkryhx** [comment]
搭车问下 这个open_ai.py 源码中有没有区分用户session会话的代码呢？我没有找到

**Comment by lmovse** [comment]
> 搭车问下 这个open_ai.py 源码中有没有区分用户session会话的代码呢？我没有找到

这个是应用端控制的

**Comment by zengqingfu1442** [comment]
```
The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/
```
直接换成下面这个更好
```
yield json.dumps(chunk.model_dump(exclude_unset=True), ensure_ascii=False)
```
