### ISSUE TITLE
[BUG/Help] <title>执行命令时报cuda out of memory错</title>

### ISSUE THREAD

**Issue by ecchiaru114514** [THUDM/ChatGLM2-6B#318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在执行
`model = AutoModel.from_pretrained("D:\DL\chatglm\ChatGLM2-6B\THUDM\chatglm2-6b", trust_remote_code=True, device='cuda')`
时，报错如下：
```
>>> model = AutoModel.from_pretrained("D:\DL\chatglm\ChatGLM2-6B\THUDM\chatglm2-6b", trust_remote_code=True, device='cuda')
Traceback (most recent call last):
  File "< stdin>", line 1, in < module>
  File "C:\Users\Henry\anaconda3\envs\chatglm\lib\site-packages\transformers\models\auto\auto_factory.py", line 479, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\Henry\anaconda3\envs\chatglm\lib\site-packages\transformers\modeling_utils.py", line 2675, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "C:\Users\Henry/.cache\huggingface\modules\transformers_modules\chatglm2-6b\modeling_chatglm.py", line 854, in __init__
    self.transformer = ChatGLMModel(config, empty_init=empty_init, device=device)
  File "C:\Users\Henry/.cache\huggingface\modules\transformers_modules\chatglm2-6b\modeling_chatglm.py", line 755, in __init__
    self.output_layer = init_method(nn.Linear, config.hidden_size, config.padded_vocab_size, bias=False,
  File "C:\Users\Henry\anaconda3\envs\chatglm\lib\site-packages\torch\nn\utils\init.py", line 52, in skip_init
    return module_cls(*args, **kwargs).to_empty(device=final_device)
  File "C:\Users\Henry\anaconda3\envs\chatglm\lib\site-packages\torch\nn\modules\module.py", line 1024, in to_empty
    return self._apply(lambda t: torch.empty_like(t, device=device))
  File "C:\Users\Henry\anaconda3\envs\chatglm\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\Henry\anaconda3\envs\chatglm\lib\site-packages\torch\nn\modules\module.py", line 1024, in <lambda>
    return self._apply(lambda t: torch.empty_like(t, device=device))
  File "C:\Users\Henry\anaconda3\envs\chatglm\lib\site-packages\torch\_refs\__init__.py", line 4254, in empty_like
    return torch.empty_strided(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 508.00 MiB (GPU 0; 11.99 GiB total capacity; 11.16 GiB already allocated; 0 bytes free; 11.16 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### Expected Behavior

gpu为nVidia GeForce RTX 4070ti，显存为12GB，且使用的模型是**chatglm2-6b-int4**，因此模型应当正常加载。
同时，在执行该命令前，vram占用仅为5%。执行命令后，占用为100%。

### Steps To Reproduce

n/a

### Environment

```markdown
- OS:Windows10 pro 22H2
- Python:3.10.12
- Transformers:4.30.2
- PyTorch:2.0.1+cu118
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by duzx16** [comment]
不要设置 `device='cuda'`，用 `.cuda()`

**Comment by ponponon** [comment]
> 不要设置 `device='cuda'`，用 `.cuda()`

两者不应该是等效的吗？为什么会有区别呢？
