### ISSUE TITLE
[BUG/Help] <mac M2max微调报NCCL 错误，请问怎么修正>

### ISSUE THREAD

**Issue by soteb** [THUDM/ChatGLM2-6B#337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

请问以下出错信息怎么处理，谢谢。
错误应该是RuntimeError: Distributed package doesn't have NCCL built in这项导致

NOTE: Redirects are currently not supported in Windows or MacOs.
master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
Traceback (most recent call last):
  File "/Users/jimmy/ai/ChatGLM2-6B/ptuning/main.py", line 413, in <module>
    main()
  File "/Users/jimmy/ai/ChatGLM2-6B/ptuning/main.py", line 56, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/chatglm2cpu/lib/python3.11/site-packages/transformers/hf_argparser.py", line 332, in parse_args_into_dataclasses
    obj = dtype(**inputs)
          ^^^^^^^^^^^^^^^
  File "<string>", line 115, in __init__
  File "/opt/homebrew/Caskroom/miniconda/base/envs/chatglm2cpu/lib/python3.11/site-packages/transformers/training_args.py", line 1259, in __post_init__
    and (self.device.type != "cuda")
         ^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/chatglm2cpu/lib/python3.11/site-packages/transformers/training_args.py", line 1694, in device
    return self._setup_devices
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/chatglm2cpu/lib/python3.11/site-packages/transformers/utils/generic.py", line 54, in __get__
    cached = self.fget(obj)
             ^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/chatglm2cpu/lib/python3.11/site-packages/transformers/training_args.py", line 1679, in _setup_devices
    torch.distributed.init_process_group(backend="nccl", timeout=self.ddp_timeout_delta)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/chatglm2cpu/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/chatglm2cpu/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1013, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 74363) of binary: /opt/homebrew/Caskroom/miniconda/base/envs/chatglm2cpu/bin/python
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/chatglm2cpu/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/chatglm2cpu/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/chatglm2cpu/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/chatglm2cpu/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/chatglm2cpu/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/chatglm2cpu/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-19_15:54:57
  host      : 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 74363)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

### Expected Behavior

微调结果

### Steps To Reproduce

bash train.sh

### Environment

```markdown
- OS:MAC M2MAX 32G
- Python:3.11.3
- Transformers:4.28.1
- Torch:2.01  或torch 2.1.0.dev20230630
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :NO
```

**Comment by zhangch9** [comment]
试试 4.30.2 版本的 transformers

**Comment by yulon** [comment]
好像是 Windows 和 Mac 没有 NCCL，pip 安装 gloo，然后在 train.sh 里面加上 --ddp_backend gloo

**Comment by soteb** [comment]
> 好像是 Windows 和 Mac 没有 NCCL，pip 安装 gloo，然后在 train.sh 里面加上 --ddp_backend gloo

感谢，您提供的方法，试过也不行。

**Comment by soteb** [comment]
> 试试 4.30.2 版本的 transformers

升级试了，错误代码有点不同，正文修改了错误输出代码，应该也是同样问题
