### ISSUE TITLE
M1 pro芯片Mac加载模型问题

### ISSUE THREAD

**Issue by lwo2002** [THUDM/ChatGLM2-6B#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

请教各位老师

### Steps To Reproduce

cli_demo和Web_demo代码调整为：
tokenizer = AutoTokenizer.from_pretrained("model/chatglm2-6b-int4", trust_remote_code=True)
model = AutoModel.from_pretrained("model/chatglm2-6b-int4", trust_remote_code=True).to('mps')
（已经安装mac最新的PyTorch-Nightly和transformers=4.30)
报错信息是cuda相关，信息如下：
Failed to load cpm_kernels:Unknown platform: darwin
Traceback (most recent call last):
  File "/Users/lwo2002/ChatGLM2-6B/cli_demo.py", line 8, in <module>
    model = AutoModel.from_pretrained("model/chatglm2-6b-int4", trust_remote_code=True).to('mps')
  File "/Users/lwo2002/miniforge3/envs/chatglm2/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 479, in from_pretrained
    return model_class.from_pretrained(
  File "/Users/lwo2002/miniforge3/envs/chatglm2/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2675, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/Users/lwo2002/.cache/huggingface/modules/transformers_modules/chatglm2-6b-int4/modeling_chatglm.py", line 772, in __init__
    self.quantize(self.config.quantization_bit, empty_init=True)
  File "/Users/lwo2002/.cache/huggingface/modules/transformers_modules/chatglm2-6b-int4/modeling_chatglm.py", line 1105, in quantize
    self.transformer.encoder = quantize(self.transformer.encoder, bits, empty_init=empty_init, device=device,
  File "/Users/lwo2002/.cache/huggingface/modules/transformers_modules/chatglm2-6b-int4/quantization.py", line 157, in quantize
    weight=layer.self_attention.query_key_value.weight.to(torch.cuda.current_device()),
  File "/Users/lwo2002/miniforge3/envs/chatglm2/lib/python3.10/site-packages/torch/cuda/__init__.py", line 707, in current_device
    _lazy_init()
  File "/Users/lwo2002/miniforge3/envs/chatglm2/lib/python3.10/site-packages/torch/cuda/__init__.py", line 258, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
请各位老师指导，谢谢。

### Environment

```markdown
- OS:mac m1 pro 
- Python:3.10
- Transformers:4.30.2
- PyTorch:PyTorch-Nightly
- mps Support:
```

**Comment by duzx16** [comment]
Mac 的 MPS 后端不支持运行量化的模型，因为量化的 kernel 是用 CUDA 写的。如果要运行量化的模型的话只能在 CPU 上。

**Comment by lwo2002** [comment]
改成：cpu也会报cuda的错，请问是什么原因呢？谢谢

**Comment by duzx16** [comment]
应该是你用的模型实现不是最新的

**Comment by lwo2002** [comment]
是昨天晚上从抱抱脸下载的，是最新的模型吧，又迭代了吗？

**Comment by ponponon** [comment]
> 是昨天晚上从抱抱脸下载的，是最新的模型吧，又迭代了吗？

mac 没有 cuda，mac 只有 mps

**Comment by wwgc** [comment]
int4模型是不是不兼容m1、m2芯片
