### ISSUE TITLE
[Feature | Bug Fix] <ChatGLM2-6B-int4 使用CPU部署报错：找不到文件quantization_kernels_parallel.so>

### ISSUE THREAD

**Issue by bwj124** [THUDM/ChatGLM2-6B#352]
### Is your feature request related to a problem? Please describe.

按照Readme的描述使用CPU推理ChatGLM2-6B-int4量化版本时报错，报错信息如下：

![image-20230721201053533](https://github.com/THUDM/ChatGLM2-6B/assets/57085345/feb49cf9-99db-447a-956f-0cd7374d3022)

已完成的步骤：

1. 将模型下载至本地并使用本地路径

2. 改用.float()使用cpu

3. 已安装[[TDM-GCC](https://jmeubank.github.io/tdm-gcc/)](https://jmeubank.github.io/tdm-gcc/)，且勾选了OpenMP

### Solutions

我的解决思路是运行ChatGLM-6b-int4，如果ChatGLM-6b-int4可以运行，那么可以参照着ChatGLM-6b-int一步步调试以最终跑通ChatGLM2-6b-int4。

结果是发现ChatGLM-6b-int4也跑不通，不过已经有一些相关的[[issue](https://github.com/THUDM/ChatGLM-6B/issues/166)](https://github.com/THUDM/ChatGLM-6B/issues/166)。

参考其他issue我解决了一个问题：编译出来的`quantization_kernels_parallel.so`和`quantization_kernels.so`其实并不能用。因此上面的报错本质上其实不是文件找不到，而是文件无法加载。（相关代码在`quantization.py`的`CPUKernel`类，包括编译和加载CPU Kernel）

经过仔细阅读源码，以及参考ChatGLM-6B中的issue，我发现其实解决的办法很简单。

对于ChatGLM-6b-int4，出现问题的原因只有：编译出来的so文件有问题，因而无法被加载。（因为后来手动编译的so文件和原始的so文件大小差异明显）

关于为什么按照教程走，但是编译出的文件有问题，我想很大概率是因为我的电脑中安装了不止一个gcc，包括MingGW64以及Cygwin。因此很可能找到TDM-GCC的gcc路径，用绝对路径去手动编译可以获得可用的so文件。但是我没有尝试，而是用了上面issue中[[gongjimin推荐的gcc](https://github.com/skeeto/w64devkit/releases)](https://github.com/skeeto/w64devkit/releases)。

所以解决办法就2步：编译正确的so文件和加载正确的so文件。

有人可能有疑问：编译好正确的so文件放到所需路径不就可以了吗？我最初也是这样想的，但无奈的发现程序会重新编译c文件，因此可用的so会被覆盖再次变成不可用的so文件。

编译正确的so文件：刚才也提到了，使用[[该项目](https://github.com/skeeto/w64devkit/releases)](https://github.com/skeeto/w64devkit/releases)的GCC编译即可。命令如下：

```
gcc -fPIC -pthread -fopenmp -std=c99 quantization_kernels.c -shared -o quantization_kernels.so
gcc -fPIC -pthread -fopenmp -std=c99 quantization_kernels_parallel.c -shared -o quantization_kernels_parallel.so
```

加载正确的so文件：在加载模型的代码后加一句加载量化模型所需kernel的代码，即

```python
tokenizer = AutoTokenizer.from_pretrained("chatglm2-6b-int4", trust_remote_code=True, revision="v1.0")
model = AutoModel.from_pretrained("chatglm2-6b-int4", trust_remote_code=True, revision="v1.0").float()  #.cuda()
model = model.quantize(bits=4, kernel_file=r"E:\Code\PyCharm\PyCharmProjects\ChatGLM2\chatglm2-6b-int4\quantization_kernels.so")
```

kernel_file为你编译好的so文件路径，亲测`quantization_kernels_parallel.so`和`quantization_kernels.so`都可以运行。

如果模型是ChatGLM-6b-int4，那么到这里就可以运行了。

但是ChatGLM2-6b-int4还不行，为什么呢？我也很疑惑，我想既然chatglm可以运行了，为什么chatglm2还是有问题。于是我在模型加载kernel的部分单步调试，最终发现了：哦！原来chatglm2直接把CPU的量化版本加载kernel的代码删除了！不知道是不是因为太少人用CPU的量化模型部署了。

于是我按照chatglm的代码，把加载kernel的代码加上就可以运行了。修改的代码不是很多，就两段。

第一段是在`modeling_chatglm.py`中修改最后一个函数`quantize`中的

```python
from .quantization import quantize

if self.quantized:
    logger.info("Already quantized.")
    return self
```

修改为（参照chatglm）：

```python
from .quantization import quantize, load_cpu_kernel

if self.quantized:
    if self.device == torch.device("cpu"):
        logger.info("Already quantized, reloading cpu kernel.")
        load_cpu_kernel(**kwargs)
    else:
        logger.info("Already quantized.")
        return self

    self.quantized = True
```

第二段是在`quantization.py`的这条语句

```python
cpu_kernels = CPUKernel()
```

后面加上所需的`load_cpu_kernel`函数

```python
cpu_kernels = CPUKernel()


def load_cpu_kernel(**kwargs):
    global cpu_kernels
    cpu_kernels = CPUKernel(**kwargs)
```

OK，到这里就可以运行了。

### Additional context

省流：
1. 编译正确的so文件：
    使用[[项目](https://github.com/skeeto/w64devkit/releases)](https://github.com/skeeto/w64devkit/releases)中的gcc编译c文件生成so文件

2. 加载正确的so文件：

    ```python
    tokenizer = AutoTokenizer.from_pretrained("chatglm2-6b-int4", trust_remote_code=True)
    model = AutoModel.from_pretrained("chatglm2-6b-int4", trust_remote_code=True).float()
    model = model.quantize(bits=4, kernel_file="xxx\quantization_kernels.so")
    ```

3. 修改`modeling_chatglm.py`的函数`quantize`中的

    ```python
    from .quantization import quantize
    
    if self.quantized:
        logger.info("Already quantized.")
        return self
    ```

    为：

    ```python
    from .quantization import quantize, load_cpu_kernel
    
    if self.quantized:
        if self.device == torch.device("cpu"):
            logger.info("Already quantized, reloading cpu kernel.")
            load_cpu_kernel(**kwargs)
        else:
            logger.info("Already quantized.")
            return self
    
        self.quantized = True
    ```

4. 在`quantization.py`的这条语句

    ```python
    cpu_kernels = CPUKernel()
    ```

    后面加上`load_cpu_kernel`函数

    ```python
    cpu_kernels = CPUKernel()
    
    
    def load_cpu_kernel(**kwargs):
        global cpu_kernels
        cpu_kernels = CPUKernel(**kwargs)
    ```

**Comment by bwj124** [comment]
经测试，在CPU为`Intel(R) Core(TM) i5-10200H CPU @ 2.40GHz   2.40 GHz`的设备上，推理速度为0.1字/s，占用内存5G~5.4G

**Comment by zhjygit** [comment]
> ### Is your feature request related to a problem? Please describe.
> 按照Readme的描述使用CPU推理ChatGLM2-6B-int4量化版本时报错，报错信息如下：
> 
> ![image-20230721201053533](https://private-user-images.githubusercontent.com/57085345/255186378-feb49cf9-99db-447a-956f-0cd7374d3022.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTUyNjAsIm5iZiI6MTcwOTcxNDk2MCwicGF0aCI6Ii81NzA4NTM0NS8yNTUxODYzNzgtZmViNDljZjktOTlkYi00NDdhLTk1NmYtMGNkNzM3NGQzMDIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA4NDkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMDE4MzUzMjk4MjEwN2Y3MzU0ZTY2NGZmNTQzYjA0ZDEwZjMzM2FlMTdkNTIzNzYzNDA0N2RhNGMyMjMyZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z_kZ9wJCzIchPx3QHxeGKonE87SehL06KjGlRo88BTk)
> 
> 已完成的步骤：
> 
> 1. 将模型下载至本地并使用本地路径
> 2. 改用.float()使用cpu
> 3. 已安装[[TDM-GCC](https://jmeubank.github.io/tdm-gcc/)]([https://jmeubank.github.io/tdm-gcc/)，且勾选了OpenMP](https://jmeubank.github.io/tdm-gcc/)%EF%BC%8C%E4%B8%94%E5%8B%BE%E9%80%89%E4%BA%86OpenMP)
> 
> ### Solutions
> 我的解决思路是运行ChatGLM-6b-int4，如果ChatGLM-6b-int4可以运行，那么可以参照着ChatGLM-6b-int一步步调试以最终跑通ChatGLM2-6b-int4。
> 
> 结果是发现ChatGLM-6b-int4也跑不通，不过已经有一些相关的[[issue](https://github.com/THUDM/ChatGLM-6B/issues/166)]([https://github.com/THUDM/ChatGLM-6B/issues/166)。](https://github.com/THUDM/ChatGLM-6B/issues/166)%E3%80%82)
> 
> 参考其他issue我解决了一个问题：编译出来的`quantization_kernels_parallel.so`和`quantization_kernels.so`其实并不能用。因此上面的报错本质上其实不是文件找不到，而是文件无法加载。（相关代码在`quantization.py`的`CPUKernel`类，包括编译和加载CPU Kernel）
> 
> 经过仔细阅读源码，以及参考ChatGLM-6B中的issue，我发现其实解决的办法很简单。
> 
> 对于ChatGLM-6b-int4，出现问题的原因只有：编译出来的so文件有问题，因而无法被加载。（因为后来手动编译的so文件和原始的so文件大小差异明显）
> 
> 关于为什么按照教程走，但是编译出的文件有问题，我想很大概率是因为我的电脑中安装了不止一个gcc，包括MingGW64以及Cygwin。因此很可能找到TDM-GCC的gcc路径，用绝对路径去手动编译可以获得可用的so文件。但是我没有尝试，而是用了上面issue中[[gongjimin推荐的gcc](https://github.com/skeeto/w64devkit/releases)]([https://github.com/skeeto/w64devkit/releases)。](https://github.com/skeeto/w64devkit/releases)%E3%80%82)
> 
> 所以解决办法就2步：编译正确的so文件和加载正确的so文件。
> 
> 有人可能有疑问：编译好正确的so文件放到所需路径不就可以了吗？我最初也是这样想的，但无奈的发现程序会重新编译c文件，因此可用的so会被覆盖再次变成不可用的so文件。
> 
> 编译正确的so文件：刚才也提到了，使用[[该项目](https://github.com/skeeto/w64devkit/releases)]([https://github.com/skeeto/w64devkit/releases)的GCC编译即可。命令如下：](https://github.com/skeeto/w64devkit/releases)%E7%9A%84GCC%E7%BC%96%E8%AF%91%E5%8D%B3%E5%8F%AF%E3%80%82%E5%91%BD%E4%BB%A4%E5%A6%82%E4%B8%8B%EF%BC%9A)
> 
> ```
> gcc -fPIC -pthread -fopenmp -std=c99 quantization_kernels.c -shared -o quantization_kernels.so
> gcc -fPIC -pthread -fopenmp -std=c99 quantization_kernels_parallel.c -shared -o quantization_kernels_parallel.so
> ```
> 
> 加载正确的so文件：在加载模型的代码后加一句加载量化模型所需kernel的代码，即
> 
> ```python
> tokenizer = AutoTokenizer.from_pretrained("chatglm2-6b-int4", trust_remote_code=True, revision="v1.0")
> model = AutoModel.from_pretrained("chatglm2-6b-int4", trust_remote_code=True, revision="v1.0").float()  #.cuda()
> model = model.quantize(bits=4, kernel_file=r"E:\Code\PyCharm\PyCharmProjects\ChatGLM2\chatglm2-6b-int4\quantization_kernels.so")
> ```
> 
> kernel_file为你编译好的so文件路径，亲测`quantization_kernels_parallel.so`和`quantization_kernels.so`都可以运行。
> 
> 如果模型是ChatGLM-6b-int4，那么到这里就可以运行了。
> 
> 但是ChatGLM2-6b-int4还不行，为什么呢？我也很疑惑，我想既然chatglm可以运行了，为什么chatglm2还是有问题。于是我在模型加载kernel的部分单步调试，最终发现了：哦！原来chatglm2直接把CPU的量化版本加载kernel的代码删除了！不知道是不是因为太少人用CPU的量化模型部署了。
> 
> 于是我按照chatglm的代码，把加载kernel的代码加上就可以运行了。修改的代码不是很多，就两段。
> 
> 第一段是在`modeling_chatglm.py`中修改最后一个函数`quantize`中的
> 
> ```python
> from .quantization import quantize
> 
> if self.quantized:
>     logger.info("Already quantized.")
>     return self
> ```
> 
> 修改为（参照chatglm）：
> 
> ```python
> from .quantization import quantize, load_cpu_kernel
> 
> if self.quantized:
>     if self.device == torch.device("cpu"):
>         logger.info("Already quantized, reloading cpu kernel.")
>         load_cpu_kernel(**kwargs)
>     else:
>         logger.info("Already quantized.")
>         return self
> 
>     self.quantized = True
> ```
> 
> 第二段是在`quantization.py`的这条语句
> 
> ```python
> cpu_kernels = CPUKernel()
> ```
> 
> 后面加上所需的`load_cpu_kernel`函数
> 
> ```python
> cpu_kernels = CPUKernel()
> 
> 
> def load_cpu_kernel(**kwargs):
>     global cpu_kernels
>     cpu_kernels = CPUKernel(**kwargs)
> ```
> 
> OK，到这里就可以运行了。
> 
> ### Additional context
> 省流：
> 
> 1. 编译正确的so文件：
>    使用[[项目](https://github.com/skeeto/w64devkit/releases)]([https://github.com/skeeto/w64devkit/releases)中的gcc编译c文件生成so文件](https://github.com/skeeto/w64devkit/releases)%E4%B8%AD%E7%9A%84gcc%E7%BC%96%E8%AF%91c%E6%96%87%E4%BB%B6%E7%94%9F%E6%88%90so%E6%96%87%E4%BB%B6)
> 2. 加载正确的so文件：
>    ```python
>    tokenizer = AutoTokenizer.from_pretrained("chatglm2-6b-int4", trust_remote_code=True)
>    model = AutoModel.from_pretrained("chatglm2-6b-int4", trust_remote_code=True).float()
>    model = model.quantize(bits=4, kernel_file="xxx\quantization_kernels.so")
>    ```
> 3. 修改`modeling_chatglm.py`的函数`quantize`中的
>    ```python
>    from .quantization import quantize
>    
>    if self.quantized:
>        logger.info("Already quantized.")
>        return self
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    为：
>    ```python
>    from .quantization import quantize, load_cpu_kernel
>    
>    if self.quantized:
>        if self.device == torch.device("cpu"):
>            logger.info("Already quantized, reloading cpu kernel.")
>            load_cpu_kernel(**kwargs)
>        else:
>            logger.info("Already quantized.")
>            return self
>    
>        self.quantized = True
>    ```
> 4. 在`quantization.py`的这条语句
>    ```python
>    cpu_kernels = CPUKernel()
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    后面加上`load_cpu_kernel`函数
>    ```python
>    cpu_kernels = CPUKernel()
>    
>    
>    def load_cpu_kernel(**kwargs):
>        global cpu_kernels
>        cpu_kernels = CPUKernel(**kwargs)
>    ```

试了一下，还行不行呀。
Load parallel cpu kernel failed C:\Users\thtfpc\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization_kernels_parallel.so: Traceback (most recent call last):
  File "C:\Users\thtfpc/.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization.py", line 148, in __init__
    kernels = ctypes.cdll.LoadLibrary(kernel_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thtfpc\anaconda3\Lib\ctypes\__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thtfpc\anaconda3\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

Load cpu kernel C:\Users\thtfpc\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization_kernels.so failed: Traceback (most recent call last):
  File "C:\Users\thtfpc/.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization.py", line 165, in __init__
    kernels = ctypes.cdll.LoadLibrary(kernel_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thtfpc\anaconda3\Lib\ctypes\__init__.py", line 454, in LoadLibrary
    return self._dlltype(name)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thtfpc\anaconda3\Lib\ctypes\__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

Traceback (most recent call last):
  File "E:\GPT\chatglm2-6b-int4\openai_api.py", line 172, in <module>
    model = model.quantize(bits=4, kernel_file=r"E:\\GPT\\chatglm2-6b-int4\\quantization_kernels.so")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thtfpc/.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 1209, in quantize
    self.transformer.encoder = quantize(self.transformer.encoder, bits, empty_init=empty_init, device=device,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: quantize() got an unexpected keyword argument 'kernel_file'

**Comment by QWQyyy** [comment]
> > ### Is your feature request related to a problem? Please describe.
> > 按照Readme的描述使用CPU推理ChatGLM2-6B-int4量化版本时报错，报错信息如下：
> > ![image-20230721201053533](https://private-user-images.githubusercontent.com/57085345/255186378-feb49cf9-99db-447a-956f-0cd7374d3022.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MTUyNjAsIm5iZiI6MTcwOTcxNDk2MCwicGF0aCI6Ii81NzA4NTM0NS8yNTUxODYzNzgtZmViNDljZjktOTlkYi00NDdhLTk1NmYtMGNkNzM3NGQzMDIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA4NDkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMDE4MzUzMjk4MjEwN2Y3MzU0ZTY2NGZmNTQzYjA0ZDEwZjMzM2FlMTdkNTIzNzYzNDA0N2RhNGMyMjMyZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z_kZ9wJCzIchPx3QHxeGKonE87SehL06KjGlRo88BTk)
> > 已完成的步骤：
> > 
> > 1. 将模型下载至本地并使用本地路径
> > 2. 改用.float()使用cpu
> > 3. 已安装[[TDM-GCC](https://jmeubank.github.io/tdm-gcc/)]([https://jmeubank.github.io/tdm-gcc/)，且勾选了OpenMP](https://jmeubank.github.io/tdm-gcc/)%EF%BC%8C%E4%B8%94%E5%8B%BE%E9%80%89%E4%BA%86OpenMP)
> > 
> > ### Solutions
> > 我的解决思路是运行ChatGLM-6b-int4，如果ChatGLM-6b-int4可以运行，那么可以参照着ChatGLM-6b-int一步步调试以最终跑通ChatGLM2-6b-int4。
> > 结果是发现ChatGLM-6b-int4也跑不通，不过已经有一些相关的[[issue](https://github.com/THUDM/ChatGLM-6B/issues/166)]([https://github.com/THUDM/ChatGLM-6B/issues/166)。](https://github.com/THUDM/ChatGLM-6B/issues/166)%E3%80%82)
> > 参考其他issue我解决了一个问题：编译出来的`quantization_kernels_parallel.so`和`quantization_kernels.so`其实并不能用。因此上面的报错本质上其实不是文件找不到，而是文件无法加载。（相关代码在`quantization.py`的`CPUKernel`类，包括编译和加载CPU Kernel）
> > 经过仔细阅读源码，以及参考ChatGLM-6B中的issue，我发现其实解决的办法很简单。
> > 对于ChatGLM-6b-int4，出现问题的原因只有：编译出来的so文件有问题，因而无法被加载。（因为后来手动编译的so文件和原始的so文件大小差异明显）
> > 关于为什么按照教程走，但是编译出的文件有问题，我想很大概率是因为我的电脑中安装了不止一个gcc，包括MingGW64以及Cygwin。因此很可能找到TDM-GCC的gcc路径，用绝对路径去手动编译可以获得可用的so文件。但是我没有尝试，而是用了上面issue中[[gongjimin推荐的gcc](https://github.com/skeeto/w64devkit/releases)]([https://github.com/skeeto/w64devkit/releases)。](https://github.com/skeeto/w64devkit/releases)%E3%80%82)
> > 所以解决办法就2步：编译正确的so文件和加载正确的so文件。
> > 有人可能有疑问：编译好正确的so文件放到所需路径不就可以了吗？我最初也是这样想的，但无奈的发现程序会重新编译c文件，因此可用的so会被覆盖再次变成不可用的so文件。
> > 编译正确的so文件：刚才也提到了，使用[[该项目](https://github.com/skeeto/w64devkit/releases)]([https://github.com/skeeto/w64devkit/releases)的GCC编译即可。命令如下：](https://github.com/skeeto/w64devkit/releases)%E7%9A%84GCC%E7%BC%96%E8%AF%91%E5%8D%B3%E5%8F%AF%E3%80%82%E5%91%BD%E4%BB%A4%E5%A6%82%E4%B8%8B%EF%BC%9A)
> > ```
> > gcc -fPIC -pthread -fopenmp -std=c99 quantization_kernels.c -shared -o quantization_kernels.so
> > gcc -fPIC -pthread -fopenmp -std=c99 quantization_kernels_parallel.c -shared -o quantization_kernels_parallel.so
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 加载正确的so文件：在加载模型的代码后加一句加载量化模型所需kernel的代码，即
> > ```python
> > tokenizer = AutoTokenizer.from_pretrained("chatglm2-6b-int4", trust_remote_code=True, revision="v1.0")
> > model = AutoModel.from_pretrained("chatglm2-6b-int4", trust_remote_code=True, revision="v1.0").float()  #.cuda()
> > model = model.quantize(bits=4, kernel_file=r"E:\Code\PyCharm\PyCharmProjects\ChatGLM2\chatglm2-6b-int4\quantization_kernels.so")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > kernel_file为你编译好的so文件路径，亲测`quantization_kernels_parallel.so`和`quantization_kernels.so`都可以运行。
> > 如果模型是ChatGLM-6b-int4，那么到这里就可以运行了。
> > 但是ChatGLM2-6b-int4还不行，为什么呢？我也很疑惑，我想既然chatglm可以运行了，为什么chatglm2还是有问题。于是我在模型加载kernel的部分单步调试，最终发现了：哦！原来chatglm2直接把CPU的量化版本加载kernel的代码删除了！不知道是不是因为太少人用CPU的量化模型部署了。
> > 于是我按照chatglm的代码，把加载kernel的代码加上就可以运行了。修改的代码不是很多，就两段。
> > 第一段是在`modeling_chatglm.py`中修改最后一个函数`quantize`中的
> > ```python
> > from .quantization import quantize
> > 
> > if self.quantized:
> >     logger.info("Already quantized.")
> >     return self
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 修改为（参照chatglm）：
> > ```python
> > from .quantization import quantize, load_cpu_kernel
> > 
> > if self.quantized:
> >     if self.device == torch.device("cpu"):
> >         logger.info("Already quantized, reloading cpu kernel.")
> >         load_cpu_kernel(**kwargs)
> >     else:
> >         logger.info("Already quantized.")
> >         return self
> > 
> >     self.quantized = True
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 第二段是在`quantization.py`的这条语句
> > ```python
> > cpu_kernels = CPUKernel()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 后面加上所需的`load_cpu_kernel`函数
> > ```python
> > cpu_kernels = CPUKernel()
> > 
> > 
> > def load_cpu_kernel(**kwargs):
> >     global cpu_kernels
> >     cpu_kernels = CPUKernel(**kwargs)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > OK，到这里就可以运行了。
> > ### Additional context
> > 省流：
> > 
> > 1. 编译正确的so文件：
> >    使用[[项目](https://github.com/skeeto/w64devkit/releases)]([https://github.com/skeeto/w64devkit/releases)中的gcc编译c文件生成so文件](https://github.com/skeeto/w64devkit/releases)%E4%B8%AD%E7%9A%84gcc%E7%BC%96%E8%AF%91c%E6%96%87%E4%BB%B6%E7%94%9F%E6%88%90so%E6%96%87%E4%BB%B6)
> > 2. 加载正确的so文件：
> >    ```python
> >    tokenizer = AutoTokenizer.from_pretrained("chatglm2-6b-int4", trust_remote_code=True)
> >    model = AutoModel.from_pretrained("chatglm2-6b-int4", trust_remote_code=True).float()
> >    model = model.quantize(bits=4, kernel_file="xxx\quantization_kernels.so")
> >    ```
> > 3. 修改`modeling_chatglm.py`的函数`quantize`中的
> >    ```python
> >    from .quantization import quantize
> >    
> >    if self.quantized:
> >        logger.info("Already quantized.")
> >        return self
> >    ```
> >    
> >    
> >        
> >          
> >        
> >    
> >          
> >        
> >    
> >        
> >      
> >    为：
> >    ```python
> >    from .quantization import quantize, load_cpu_kernel
> >    
> >    if self.quantized:
> >        if self.device == torch.device("cpu"):
> >            logger.info("Already quantized, reloading cpu kernel.")
> >            load_cpu_kernel(**kwargs)
> >        else:
> >            logger.info("Already quantized.")
> >            return self
> >    
> >        self.quantized = True
> >    ```
> > 4. 在`quantization.py`的这条语句
> >    ```python
> >    cpu_kernels = CPUKernel()
> >    ```
> >    
> >    
> >        
> >          
> >        
> >    
> >          
> >        
> >    
> >        
> >      
> >    后面加上`load_cpu_kernel`函数
> >    ```python
> >    cpu_kernels = CPUKernel()
> >    
> >    
> >    def load_cpu_kernel(**kwargs):
> >        global cpu_kernels
> >        cpu_kernels = CPUKernel(**kwargs)
> >    ```
> 
> 试了一下，还行不行呀。 Load parallel cpu kernel failed C:\Users\thtfpc.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization_kernels_parallel.so: Traceback (most recent call last): File "C:\Users\thtfpc/.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization.py", line 148, in **init** kernels = ctypes.cdll.LoadLibrary(kernel_file) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\thtfpc\anaconda3\Lib\ctypes__init__.py", line 454, in LoadLibrary return self._dlltype(name) ^^^^^^^^^^^^^^^^^^^ File "C:\Users\thtfpc\anaconda3\Lib\ctypes__init__.py", line 376, in **init** self._handle = _dlopen(self._name, mode) ^^^^^^^^^^^^^^^^^^^^^^^^^ OSError: [WinError 193] %1 不是有效的 Win32 应用程序。
> 
> Load cpu kernel C:\Users\thtfpc.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization_kernels.so failed: Traceback (most recent call last): File "C:\Users\thtfpc/.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization.py", line 165, in **init** kernels = ctypes.cdll.LoadLibrary(kernel_file) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\thtfpc\anaconda3\Lib\ctypes__init__.py", line 454, in LoadLibrary return self._dlltype(name) ^^^^^^^^^^^^^^^^^^^ File "C:\Users\thtfpc\anaconda3\Lib\ctypes__init__.py", line 376, in **init** self._handle = _dlopen(self._name, mode) ^^^^^^^^^^^^^^^^^^^^^^^^^ OSError: [WinError 193] %1 不是有效的 Win32 应用程序。
> 
> Traceback (most recent call last): File "E:\GPT\chatglm2-6b-int4\openai_api.py", line 172, in model = model.quantize(bits=4, kernel_file=r"E:\GPT\chatglm2-6b-int4\quantization_kernels.so") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\thtfpc/.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 1209, in quantize self.transformer.encoder = quantize(self.transformer.encoder, bits, empty_init=empty_init, device=device, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: quantize() got an unexpected keyword argument 'kernel_file'

+111111111111111111111111
我也是这样，毛用没有，准备迁移到Docker linux系统上试试看了
