### ISSUE TITLE
[Help] int4版本的模型名字是否是THUDM/chatglm2-6b-int4，离线模式的cache_dir是否可用？

### ISSUE THREAD

**Issue by iaston** [THUDM/ChatGLM2-6B#368]
我在九天上运行int4版本，因为九天无法连接huggingface.co，所以我先下载好模型文件，再用cache_dir指定目录，但运行时总是去下载（当然总是失败）
/root/gpt/ChatGLM2-6B/int4/目录下：
total 3835411
-rw-r--r-- 1 root root       2356 Jul 24 20:20 MODEL_LICENSE.txt
-rw-r--r-- 1 root root       7687 Jul 24 20:20 README.md
-rw-r--r-- 1 root root       1168 Jul 24 20:20 config.json
-rw-r--r-- 1 root root       2246 Jul 24 20:16 configuration_chatglm.py
-rw-r--r-- 1 root root      50717 Jul 24 20:16 modeling_chatglm.py
-rw-r--r-- 1 root root 3923712365 Jul 24 19:51 pytorch_model.bin
-rw-r--r-- 1 root root      44295 Jul 24 20:16 pytorch_model.bin.index.json
-rw-r--r-- 1 root root    2606234 Jul 24 20:16 quantization.py
-rw-r--r-- 1 root root      10002 Jul 24 20:16 tokenization_chatglm.py
-rw-r--r-- 1 root root    1018370 Jul 24 20:16 tokenizer.model
-rw-r--r-- 1 root root        243 Jul 24 20:16 tokenizer_config.json
===================================================

api.py我修改了一下：
import os
os.environ["HUGGINGFACE_OFFLINE"] = "True"
if __name__ == '__main__':
    tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm2-6b-int4", cache_dir="/root/gpt/ChatGLM2-6B/int4/",trust_remote_code=True)
    model = AutoModel.from_pretrained("THUDM/chatglm2-6b-int4", cache_dir="/root/gpt/ChatGLM2-6B/int4/",trust_remote_code=True).half().cuda()
    
结果还是出错了，**请教我哪里做错了？**

python api.py
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 21956644-f3bd-4e97-a3e6-d26a37edbe46)')' thrown while requesting HEAD https://huggingface.co/THUDM/chatglm2-6b-int4/resolve/main/tokenizer_config.json
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 69b12c77-fe0e-4b2d-bfe4-9898df3229f4)')' thrown while requesting HEAD https://huggingface.co/THUDM/chatglm2-6b-int4/resolve/main/tokenization_chatglm.py
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 62ccae5d-c1ab-4953-8059-69c2e2202c56)')' thrown while requesting HEAD https://huggingface.co/THUDM/chatglm2-6b-int4/resolve/main/tokenizer.model
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: d1ea8cd4-7fee-4a72-8ca3-05f2a96c0de2)')' thrown while requesting HEAD https://huggingface.co/THUDM/chatglm2-6b-int4/resolve/main/added_tokens.json
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: c1eb4bdb-998c-4a1f-a0d4-465aff6a3a99)')' thrown while requesting HEAD https://huggingface.co/THUDM/chatglm2-6b-int4/resolve/main/special_tokens_map.json
Traceback (most recent call last):
  File "/root/gpt/ChatGLM2-6B/api.py", line 57, in <module>
    tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm2-6b-int4", cache_dir="/root/gpt/ChatGLM2-6B/int4/",trust_remote_code=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/conda/envs/311/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 689, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/conda/envs/311/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1841, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/conda/envs/311/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2004, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm2-6b-int4/5579a9f4c07b1dde911efedfba78af372aacd93a/tokenization_chatglm.py", line 73, in __init__
    self.tokenizer = SPTokenizer(vocab_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm2-6b-int4/5579a9f4c07b1dde911efedfba78af372aacd93a/tokenization_chatglm.py", line 13, in __init__
    assert os.path.isfile(model_path), model_path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 30, in isfile
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
(311) root@dl-230602193348ajc-pod-jupyter-85d8cbb8cd-87ncn:~/gpt/ChatGLM2-6B# python api.py
urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1002)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/conda/envs/311/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/root/.local/conda/envs/311/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/root/.local/conda/envs/311/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /THUDM/chatglm2-6b/resolve/main/tokenizer_config.json (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1002)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/gpt/ChatGLM2-6B/api.py", line 57, in <module>
    tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm2-6b", cache_dir="/root/gpt/ChatGLM2-6B/int4/",trust_remote_code=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/conda/envs/311/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 652, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/conda/envs/311/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 496, in get_tokenizer_config
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "/root/.local/conda/envs/311/lib/python3.11/site-packages/transformers/utils/hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "/root/.local/conda/envs/311/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/.local/conda/envs/311/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1195, in hf_hub_download
    metadata = get_hf_file_metadata(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/conda/envs/311/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/.local/conda/envs/311/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1532, in get_hf_file_metadata
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "/root/.local/conda/envs/311/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 407, in _request_wrapper
    response = _request_wrapper(
               ^^^^^^^^^^^^^^^^^
  File "/root/.local/conda/envs/311/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 442, in _request_wrapper
    return http_backoff(
           ^^^^^^^^^^^^^
  File "/root/.local/conda/envs/311/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 258, in http_backoff
    response = session.request(method=method, url=url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/conda/envs/311/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/conda/envs/311/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/conda/envs/311/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/conda/envs/311/lib/python3.11/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /THUDM/chatglm2-6b/resolve/main/tokenizer_config.json (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1002)')))"), '(Request ID: 42a8a489-5d22-4cd7-8bf9-94218494e8b5)')
(311) root@dl-230602193348ajc-pod-jupyter-85d8cbb8cd-87ncn:~/gpt/ChatGLM2-6B# python api.py
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 18c679d7-e0f3-4087-bd35-61ddcbe42920)')' thrown while requesting HEAD https://huggingface.co/THUDM/chatglm2-6b-int4/resolve/main/tokenizer_config.json
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: daefd44e-1fcb-4ab0-ac6c-5b6a3889c57b)')' thrown while requesting HEAD https://huggingface.co/THUDM/chatglm2-6b-int4/resolve/main/tokenization_chatglm.py
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 879626fe-5afd-4922-8024-fdb9bec55427)')' thrown while requesting HEAD https://huggingface.co/THUDM/chatglm2-6b-int4/resolve/main/tokenizer.model
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 78940268-9242-4c1a-8fc2-ec37d71b73ba)')' thrown while requesting HEAD https://huggingface.co/THUDM/chatglm2-6b-int4/resolve/main/added_tokens.json
'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: 03f9e944-11a1-48a1-81f8-8320f59c2ed6)')' thrown while requesting HEAD https://huggingface.co/THUDM/chatglm2-6b-int4/resolve/main/special_tokens_map.json
Traceback (most recent call last):
  File "/root/gpt/ChatGLM2-6B/api.py", line 57, in <module>
    tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm2-6b-int4", cache_dir="/root/gpt/ChatGLM2-6B/int4/",trust_remote_code=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/conda/envs/311/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 678, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/conda/envs/311/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/conda/envs/311/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1988, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm2-6b-int4/5579a9f4c07b1dde911efedfba78af372aacd93a/tokenization_chatglm.py", line 73, in __init__
    self.tokenizer = SPTokenizer(vocab_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm2-6b-int4/5579a9f4c07b1dde911efedfba78af372aacd93a/tokenization_chatglm.py", line 13, in __init__
    assert os.path.isfile(model_path), model_path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 30, in isfile
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### Steps To Reproduce

如上

### Environment

```markdown
- OS:ubuntu 
- Python: 3.10
- Transformers: 4.31
- PyTorch: 2.01
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by hl99** [comment]
THUDM/chatglm2-6b-int4 直接改成本地的这个路径:"/root/gpt/ChatGLM2-6B/int4/"。缓存路径不需要了。

**Comment by evyy1234** [comment]
请问楼主解决了吗，我也遇到这个问题，一直解决不了，请不吝赐教

**Comment by mulichang2017** [comment]
配置如下环境变量可以解决：
TRANSFORMERS_CACHE：pathtomodel\chatglm2-6b-int4
