### ISSUE TITLE
[BUG/Help] 我希望能够产出稳定的结果，但是设置了temperature为0就报错，尝试了一下，最低只能设置0.001

### ISSUE THREAD

**Issue by 143230** [THUDM/ChatGLM2-6B#390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Traceback (most recent call last):
  File "/root/anaconda3/envs/langchain/lib/python3.8/site-packages/gradio/routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "/root/anaconda3/envs/langchain/lib/python3.8/site-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/root/anaconda3/envs/langchain/lib/python3.8/site-packages/gradio/blocks.py", line 1035, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/anaconda3/envs/langchain/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/anaconda3/envs/langchain/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/root/anaconda3/envs/langchain/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/root/anaconda3/envs/langchain/lib/python3.8/site-packages/gradio/utils.py", line 491, in async_iteration
    return next(iterator)
  File "web_demo.py", line 65, in predict
    for response, history, past_key_values in model.stream_chat(tokenizer, input, history, past_key_values=past_key_values,
  File "/root/anaconda3/envs/langchain/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py", line 1058, in stream_chat
    for outputs in self.stream_generate(**inputs, past_key_values=past_key_values,
  File "/root/anaconda3/envs/langchain/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py", line 1136, in stream_generate
    logits_warper = self._get_logits_warper(generation_config)
  File "/root/anaconda3/envs/langchain/lib/python3.8/site-packages/transformers/generation/utils.py", line 803, in _get_logits_warper
    warpers.append(TemperatureLogitsWarper(generation_config.temperature))
  File "/root/anaconda3/envs/langchain/lib/python3.8/site-packages/transformers/generation/logits_process.py", line 177, in __init__
    raise ValueError(f"`temperature` has to be a strictly positive float, but is {temperature}")
ValueError: `temperature` has to be a strictly positive float, but is 0

### Expected Behavior

temperature=0也能正常运行，并产出稳定的结果

### Steps To Reproduce

1. python web_demo.py
2. 页面设置temperature=0，top_p=1
3. 输入你好
4. 后台报错

### Environment

```markdown
- OS: centos8
- Python: 3.8.16
- Transformers:
- PyTorch:
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by duzx16** [comment]
可以设置 `do_sample=False`
