### ISSUE TITLE
[BUG/Help] <'ChatGLMModel' object has no attribute 'prefix_encoder'>

### ISSUE THREAD

**Issue by ymx10086** [THUDM/ChatGLM2-6B#402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

(chatglm2-6b) ➜  ChatGLM2-6B git:(main) ✗ python web_demo.py Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:09<00:00,  1.29s/it] Traceback (most recent call last):   File "web_demo.py", line 21, in <module>     model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)   File "/home/ymx10086/.conda/envs/chatglm2-6b/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__     raise AttributeError("'{}' object has no attribute '{}'".format( AttributeError: 'ChatGLMModel' object has no attribute 'prefix_encoder'

### Steps To Reproduce

和项目完全相同

### Environment

```markdown
- OS:ubuntu20.04
- Python:3.8.0
- Transformers:4.30.2
- PyTorch:2.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :12.1
```

**Comment by zhaofangtao** [comment]
我也是这样问题，修改模型中的pre_seq_len:None为pre_seq_len:128 使之和训练脚本测试脚本的这个值一致，都不行。重新训练出来的微调模型还是这问题

**Comment by AlexasXu** [comment]
更新下模型文件就行了，模型文件改了

**Comment by Garen-in-bush** [comment]
打开模型文件目录
编辑configuration_chatglm文件
修改参数
![image](https://github.com/THUDM/ChatGLM2-6B/assets/50519434/a84b8bdd-683b-42bc-8f87-1c7447489301)
这个报错是没有加载prefix_encoder造成的

**Comment by haqishen** [comment]
```
backbone = "THUDM/chatglm2-6b-32k"

config = AutoConfig.from_pretrained(backbone, trust_remote_code=True)
config.pre_seq_len = 128  # 改成你FT时的参数
config.prefix_projection = True

tokenizer = AutoTokenizer.from_pretrained(backbone, trust_remote_code=True)
model = AutoModel.from_pretrained(backbone, trust_remote_code=True, config=config, device='cpu')

CHECKPOINT_PATH = './output/xxxx'  # 改成你FT时输出的文件夹
prefix_state_dict = torch.load(os.path.join(CHECKPOINT_PATH, "pytorch_model.bin"))
new_prefix_state_dict = {}
for k, v in prefix_state_dict.items():
    if k.startswith("transformer.prefix_encoder."):
        new_prefix_state_dict[k[len("transformer.prefix_encoder."):]] = v
model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict, strict=False)

model = model.cuda()
model = model.eval()
```
