### ISSUE TITLE
[BUG/Help] <Error(s) in loading state_dict for ChatGLMForConditionalGeneration>

### ISSUE THREAD

**Issue by luhuaei** [THUDM/ChatGLM2-6B#423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

根据 READMD 中的教程，我从 [清华云盘](https://cloud.tsinghua.edu.cn/d/674208019e314311ab5c/?p=%2Fchatglm2-6b-int4&mode=list) 中下载了 chatglm2-6b-int4 的模型数据，然后将 cli_demo.py 中更改相关的路径，更改如下所示: 
```
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm2-6b-int4", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/chatglm2-6b-int4", trust_remote_code=True).float()
# 多显卡支持，使用下面两行代替上面一行，将num_gpus改为你实际的显卡数量
# from utils import load_model_on_gpus
# model = load_model_on_gpus("THUDM/chatglm2-6b", num_gpus=2)
model = model.eval()
```

但在执行的时候，会出现下面的错误
```
Traceback (most recent call last):
  File "/ChatGLM2-6B/cli_demo.py", line 8, in <module>
    model = AutoModel.from_pretrained("THUDM/chatglm2-6b-int4", trust_remote_code=True).float()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 479, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2881, in from_pretrained
    ) = cls._load_pretrained_model(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3278, in _load_pretrained_model
    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for ChatGLMForConditionalGeneration:
	size mismatch for transformer.encoder.layers.0.self_attention.query_key_value.weight: copying a param with shape torch.Size([4608, 2048]) from checkpoint, the shape in current model is torch.Size([4608, 4096]).
	size mismatch for transformer.encoder.layers.0.self_attention.dense.weight: copying a param with shape torch.Size([4096, 2048]) from checkpoint, the shape in current model is torch.Size([4096, 4096]).
...
size mismatch for transformer.encoder.layers.27.mlp.dense_4h_to_h.weight: copying a param with shape torch.Size([4096, 6848]) from checkpoint, the shape in current model is torch.Size([4096, 13696]).
	You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.
```

我尝试按照上面的提示添加 `ignore_mismatched_sizes=True` 到 `from_pretrained` 中去后，发现模型确实可以运行起来，但会回答完全不相关的回答。
![image](https://github.com/THUDM/ChatGLM2-6B/assets/46041665/d1c0d97a-ebb7-47a6-a435-6735a0c61e2a)

### Expected Behavior

能正常的使用

### Steps To Reproduce

1. 从上面描述的地址中下载 chatglm2-6b-int4 模型
2. 更改对应的路径地址
3. 执行 python cli_demo.py

### Environment

```markdown
- OS: Debian 11 (bullseye)
- Python: Python 3.11.4
- Transformers: 4.30.2
- PyTorch: '2.0.1+cu117'
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : False
```

### Anything else?

为什么会输出不相关的内容(有时还会输出各种各样语言的字符，看起来像乱码一样)?

**Comment by AB-pixel-pixel** [comment]
我感觉没输出相关内容就是因为模型没有正确利用自身参数。问题来源于mismatch。我通过使用hugging face的下载解决了这个问题。放弃了使用云盘。hugging face的那个checkpoint能搞定问题。

**Comment by luhuaei** [comment]
> 我感觉没输出相关内容就是因为模型没有正确利用自身参数。问题来源于mismatch。我通过使用hugging face的下载解决了这个问题。放弃了使用云盘。hugging face的那个checkpoint能搞定问题。

感谢！试了从 huggin face 中下载 chatglm-6b-int4 模型，正常了。: )
