### ISSUE TITLE
[BUG/Help] <title> 用int4量化微调，12G显存仍然不够

### ISSUE THREAD

**Issue by hzt97** [THUDM/ChatGLM2-6B#447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

train.bat配置如下
`python main.py ^
--do_train ^
--train_file data\ocean\train.json ^
--validation_file data\ocean\dev.json ^
--preprocessing_num_workers 10 ^
--prompt_column content ^
--response_column summary ^
--overwrite_cache ^
--model_name_or_path D:\hzt\pycodes\ChatGLM2-6B\chatglm2-6b-int4 ^
--output_dir D:\hzt\pycodes\ChatGLM2-6B\output ^
--overwrite_output_dir ^
--max_source_length 64 ^
--max_target_length 128 ^
--per_device_train_batch_size 1 ^
--per_device_eval_batch_size 1 ^
--gradient_accumulation_steps 8 ^
--predict_with_generate ^
--max_steps 20 ^
--logging_steps 10 ^
--save_steps 10 ^
--learning_rate 2e-2 ^
--pre_seq_len 128 ^
--quantization_bit 4 ^`

错误如下
`8/10/2023 16:14:42 - WARNING - transformers_modules.chatglm2-6b-int4.modeling_chatglm - `use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
08/10/2023 16:14:42 - WARNING - transformers_modules.chatglm2-6b-int4.modeling_chatglm - `use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
D:\ProgramData\Anaconda3\envs\chatglm\lib\site-packages\torch\nn\parallel\_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
D:\ProgramData\Anaconda3\envs\chatglm\lib\site-packages\torch\cuda\nccl.py:15: UserWarning: PyTorch is not compiled with NCCL support
  warnings.warn('PyTorch is not compiled with NCCL support')
Traceback (most recent call last):
  File "D:\hzt\pycodes\ChatGLM2-6B\ptuning\main.py", line 411, in <module>
    main()
  File "D:\hzt\pycodes\ChatGLM2-6B\ptuning\main.py", line 350, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "D:\ProgramData\Anaconda3\envs\chatglm\lib\site-packages\transformers\trainer.py", line 1645, in train
    return inner_training_loop(
  File "D:\ProgramData\Anaconda3\envs\chatglm\lib\site-packages\transformers\trainer.py", line 1938, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "D:\ProgramData\Anaconda3\envs\chatglm\lib\site-packages\transformers\trainer.py", line 2770, in training_step
    self.accelerator.backward(loss)
  File "D:\ProgramData\Anaconda3\envs\chatglm\lib\site-packages\accelerate\accelerator.py", line 1853, in backward
    loss.backward(**kwargs)
  File "D:\ProgramData\Anaconda3\envs\chatglm\lib\site-packages\torch\_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "D:\ProgramData\Anaconda3\envs\chatglm\lib\site-packages\torch\autograd\__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "D:\ProgramData\Anaconda3\envs\chatglm\lib\site-packages\torch\autograd\function.py", line 274, in apply
    return user_fn(self, *args)
  File "D:\ProgramData\Anaconda3\envs\chatglm\lib\site-packages\torch\nn\parallel\_functions.py", line 34, in backward
    return (None,) + ReduceAddCoalesced.apply(ctx.input_device, ctx.num_inputs, *grad_outputs)
  File "D:\ProgramData\Anaconda3\envs\chatglm\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "D:\ProgramData\Anaconda3\envs\chatglm\lib\site-packages\torch\nn\parallel\_functions.py", line 45, in forward
    return comm.reduce_add_coalesced(grads_, destination)
  File "D:\ProgramData\Anaconda3\envs\chatglm\lib\site-packages\torch\nn\parallel\comm.py", line 143, in reduce_add_coalesced
    flat_result = reduce_add(flat_tensors, destination)
  File "D:\ProgramData\Anaconda3\envs\chatglm\lib\site-packages\torch\nn\parallel\comm.py", line 101, in reduce_add
    result = inputs[root_index] + nonroot[0].to(device=destination_device, non_blocking=True)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 54.00 MiB (GPU 0; 12.00 GiB total capacity; 10.32 GiB already allocated; 0 bytes free; 10.60 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
  0%|`

### Steps To Reproduce

Windows平台
2张3060 12G显卡

### Environment

```markdown
- OS:Windows 10
- Python:3.9
- Transformers:4.30
- PyTorch:2.0.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by huangdacheng** [comment]
同遇到一样的情况，你解决了吗

**Comment by hzt97** [comment]
> 同遇到一样的情况，你解决了吗

之前用的双卡训练，设置单卡训练就没问题了
