### ISSUE TITLE
[BUG/Help]  numpy.object

### ISSUE THREAD

**Issue by jiangweiatgithub** [THUDM/ChatGLM2-6B#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Issue with depreciated object of numpy

### Steps To Reproduce

When running the following python 3.8 script:
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained(".\\THUDM\\chatglm2-6b", trust_remote_code=True)
model = AutoModel.from_pretrained(".\\THUDM\\chatglm2-6b", trust_remote_code=True, device='cuda')
model = model.eval()
response, history = model.chat(tokenizer, "你好", history=[])
print(response)
response, history = model.chat(tokenizer, "晚上睡不着应该怎么办", history=history)
print(response)

I got:

Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
C:\Users\polyt\AppData\Roaming\Python\Python38\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:569: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  (np.object, string),
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    model = AutoModel.from_pretrained(".\\THUDM\\chatglm2-6b", trust_remote_code=True, device='cuda')
  File "C:\Users\polyt\.conda\envs\ChatGLM2-6B\lib\site-packages\transformers\models\auto\auto_factory.py", line 462, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "C:\Users\polyt\.conda\envs\ChatGLM2-6B\lib\site-packages\transformers\dynamic_module_utils.py", line 399, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "C:\Users\polyt\.conda\envs\ChatGLM2-6B\lib\site-packages\transformers\dynamic_module_utils.py", line 177, in get_class_in_module
    module = importlib.import_module(module_path)
  File "C:\Users\polyt\.conda\envs\ChatGLM2-6B\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\polyt/.cache\huggingface\modules\transformers_modules\chatglm2-6b\modeling_chatglm.py", line 21, in <module>
    from transformers.modeling_utils import PreTrainedModel
  File "C:\Users\polyt\.conda\envs\ChatGLM2-6B\lib\site-packages\transformers\modeling_utils.py", line 83, in <module>
    from accelerate import __version__ as accelerate_version
  File "C:\Users\polyt\.conda\envs\ChatGLM2-6B\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Users\polyt\.conda\envs\ChatGLM2-6B\lib\site-packages\accelerate\accelerator.py", line 40, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "C:\Users\polyt\.conda\envs\ChatGLM2-6B\lib\site-packages\accelerate\tracking.py", line 42, in <module>
    from torch.utils import tensorboard
  File "C:\Users\polyt\.conda\envs\ChatGLM2-6B\lib\site-packages\torch\utils\tensorboard\__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "C:\Users\polyt\.conda\envs\ChatGLM2-6B\lib\site-packages\torch\utils\tensorboard\writer.py", line 13, in <module>
    from tensorboard.summary.writer.event_file_writer import EventFileWriter
  File "C:\Users\polyt\AppData\Roaming\Python\Python38\site-packages\tensorboard\summary\__init__.py", line 22, in <module>
    from tensorboard.summary import v1  # noqa: F401
  File "C:\Users\polyt\AppData\Roaming\Python\Python38\site-packages\tensorboard\summary\v1.py", line 23, in <module>
    from tensorboard.plugins.histogram import summary as _histogram_summary
  File "C:\Users\polyt\AppData\Roaming\Python\Python38\site-packages\tensorboard\plugins\histogram\summary.py", line 35, in <module>
    from tensorboard.plugins.histogram import summary_v2
  File "C:\Users\polyt\AppData\Roaming\Python\Python38\site-packages\tensorboard\plugins\histogram\summary_v2.py", line 35, in <module>
    from tensorboard.util import tensor_util
  File "C:\Users\polyt\AppData\Roaming\Python\Python38\site-packages\tensorboard\util\tensor_util.py", line 20, in <module>
    from tensorboard.compat.tensorflow_stub import dtypes, compat, tensor_shape
  File "C:\Users\polyt\AppData\Roaming\Python\Python38\site-packages\tensorboard\compat\tensorflow_stub\__init__.py", line 22, in <module>
    from .dtypes import as_dtype  # noqa
  File "C:\Users\polyt\AppData\Roaming\Python\Python38\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py", line 569, in <module>
    (np.object, string),
  File "C:\Users\polyt\.conda\envs\ChatGLM2-6B\lib\site-packages\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

### Environment

```markdown
- OS: Windows 11
- Python: 3.8.16
- Transformers: 4.27.1
- PyTorch: 2.0.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by jiangweiatgithub** [comment]
FYI, I have just changed all those warned depreciated items manually and got rid of the issues.
