### ISSUE TITLE
[BUG/Help] p-tuning v2运行train.sh时wandb报错

### ISSUE THREAD

**Issue by ad1192214879** [THUDM/ChatGLM2-6B#465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[INFO|integrations.py:727] 2023-08-16 18:14:55,816 >> Automatic Weights & Biases logging enabled, to disable set os.environ["WANDB_DISABLED"] = "true"
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
wandb: Network error (ReadTimeout), entering retry loop.
wandb: Network error (ReadTimeout), entering retry loop.
Problem at: /home/aiding/anaconda3/envs/GLM2/lib/python3.11/site-packages/wandb/sdk/wandb_init.py 829 getcaller
wandb: ERROR Run initialization has timed out after 60.0 sec. 
wandb: ERROR Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/home/aiding/ChatGLM2/ChatGLM2-6B-main/ptuning/main.py", line 411, in <module>
    main()
  File "/home/aiding/ChatGLM2/ChatGLM2-6B-main/ptuning/main.py", line 350, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aiding/anaconda3/envs/GLM2/lib/python3.11/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/aiding/anaconda3/envs/GLM2/lib/python3.11/site-packages/transformers/trainer.py", line 1862, in _inner_training_loop
    self.control = self.callback_handler.on_train_begin(args, self.state, self.control)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aiding/anaconda3/envs/GLM2/lib/python3.11/site-packages/transformers/trainer_callback.py", line 353, in on_train_begin
    return self.call_event("on_train_begin", args, state, control)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aiding/anaconda3/envs/GLM2/lib/python3.11/site-packages/transformers/trainer_callback.py", line 397, in call_event
    result = getattr(callback, event)(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aiding/anaconda3/envs/GLM2/lib/python3.11/site-packages/transformers/integrations.py", line 771, in on_train_begin
    self.setup(args, state, model, **kwargs)
  File "/home/aiding/anaconda3/envs/GLM2/lib/python3.11/site-packages/transformers/integrations.py", line 745, in setup
    self._wandb.init(
  File "/home/aiding/anaconda3/envs/GLM2/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1166, in init
    raise e
  File "/home/aiding/anaconda3/envs/GLM2/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1147, in init
    run = wi.init()
          ^^^^^^^^^
  File "/home/aiding/anaconda3/envs/GLM2/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 762, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 298698) of binary: /home/aiding/anaconda3/envs/GLM2/bin/python3.11
Traceback (most recent call last):
  File "/home/aiding/anaconda3/envs/GLM2/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/aiding/anaconda3/envs/GLM2/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/aiding/anaconda3/envs/GLM2/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/aiding/anaconda3/envs/GLM2/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/aiding/anaconda3/envs/GLM2/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aiding/anaconda3/envs/GLM2/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-16_18:16:19
  host      : 10.112.221.97
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 298698)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

### Steps To Reproduce

运行ptuning中的train.sh

### Environment

```markdown
- OS:70-Ubuntu
- Python:3.10
- Transformers:4.30.2
- PyTorch:2.0.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by ASan1527** [comment]
请问大佬你解决了吗

**Comment by ad1192214879** [comment]
> 请问大佬你解决了吗

main.py里面加上os.environ["WANDB_DISABLED"] = "true"

**Comment by ASan1527** [comment]
好滴谢谢大佬

**Comment by geekplusaa** [comment]
export WANDB_DISABLED=true
