### ISSUE TITLE
[BUG/Help] <The 4-bit quantization model was used for full fine-tuning, and an error was reported when the corresponding checkpoint path was loaded>

### ISSUE THREAD

**Issue by 455670288** [THUDM/ChatGLM2-6B#467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

使用4bit量化模型进行全参数微调，使用evaluate_finetune.sh脚本加载相应的checkpoint路径时报告错误。

### Steps To Reproduce

[INFO|configuration_utils.py:667] 2023-08-17 10:28:20,658 >> loading configuration file /home/tryon/ljh/ChatGLM2-6B/ptuning/output/adgen-chatglm2-6b-ft-1e-4/checkpoint-30000/config.json
[ERROR|dynamic_module_utils.py:264] 2023-08-17 10:28:20,658 >> Could not locate the configuration_chatglm.py inside /home/tryon/ljh/ChatGLM2-6B/ptuning/output/adgen-chatglm2-6b-ft-1e-4/checkpoint-30000.
Traceback (most recent call last):
  File "/home/tryon/ljh/ChatGLM2-6B/ptuning/main.py", line 412, in <module>
    main()
  File "/home/tryon/ljh/ChatGLM2-6B/ptuning/main.py", line 106, in main
    config = AutoConfig.from_pretrained(model_args.model_name_or_path, trust_remote_code=True) 
  File "/home/tryon/anaconda3/envs/ChatGLM2-6b_ft/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 953, in from_pretrained
    config_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
  File "/home/tryon/anaconda3/envs/ChatGLM2-6b_ft/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 431, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/home/tryon/anaconda3/envs/ChatGLM2-6b_ft/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 247, in get_cached_module_file
    resolved_module_file = cached_file(
  File "/home/tryon/anaconda3/envs/ChatGLM2-6b_ft/lib/python3.9/site-packages/transformers/utils/hub.py", line 388, in cached_file
    raise EnvironmentError(
OSError: /home/tryon/ljh/ChatGLM2-6B/ptuning/output/adgen-chatglm2-6b-ft-1e-4/checkpoint-30000 does not appear to have a file named configuration_chatglm.py. Checkout 'https://huggingface.co//home/tryon/ljh/ChatGLM2-6B/ptuning/output/adgen-chatglm2-6b-ft-1e-4/checkpoint-30000/None' for available files.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 11740) of binary: /home/tryon/anaconda3/envs/ChatGLM2-6b_ft/bin/python
Traceback (most recent call last):
  File "/home/tryon/anaconda3/envs/ChatGLM2-6b_ft/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/tryon/anaconda3/envs/ChatGLM2-6b_ft/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/tryon/anaconda3/envs/ChatGLM2-6b_ft/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/tryon/anaconda3/envs/ChatGLM2-6b_ft/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/tryon/anaconda3/envs/ChatGLM2-6b_ft/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/tryon/anaconda3/envs/ChatGLM2-6b_ft/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-17_10:28:25
  host      : ai-PowerEdge-R750xa
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 11740)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

### Environment

```markdown
- OS:
- Python:3.9
- Transformers:4.23
- PyTorch:2.0
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :
```

**Comment by mojingcj** [comment]
请问您解决了这个问题吗？
