### ISSUE TITLE
[BUG/Help] 使用train.sh脚本单机8卡训练时报错

### ISSUE THREAD

**Issue by YXlukarov** [THUDM/ChatGLM2-6B#509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

目前在63w条数据上以int8精度微调模型，在8张32G的V100上微调，将PRE_SEQ_LEN设为512，max_source_length设为512，max_target_length设为16，per_device_train_batch_size设为1，gradient_accumulation_steps设为12
训练时在train dataset上Running tokenizer时报错：

> Running tokenizer on train dataset (num_proc=10):  29%|██▉       | 187000/636518 [37:10<2:29:21, 50.16 examples/s]
Running tokenizer on train dataset (num_proc=10):  30%|███       | 194000/636518 [37:10<51:06, 144.29 examples/s]
Running tokenizer on train dataset (num_proc=10):  30%|██▉       | 189000/636518 [37:11<1:22:12, 90.72 examples/s]
Running tokenizer on train dataset (num_proc=10):  31%|███       | 195000/636518 [37:12<21:35, 340.74 examples/s]WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 228365 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 228366 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 228367 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 228368 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 228369 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 228370 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 228371 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 228364) of binary: /public/home/xxx/.conda/envs/chat/bin/python
Traceback (most recent call last):
  File "/public/home/xxx/.conda/envs/chat/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.12.1', 'console_scripts', 'torchrun')())
  File "/public/home/xxx/.conda/envs/chat/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/public/home/xxx/.conda/envs/chat/lib/python3.10/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/public/home/xxx/.conda/envs/chat/lib/python3.10/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/public/home/xxx/.conda/envs/chat/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/public/home/xxx/.conda/envs/chat/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

是否是数据量过大的原因？

### Steps To Reproduce

```Shell
#!/bin/bash
#SBATCH -p gpu8Q
#SBATCH -q gpuq
#SBATCH --gres=gpu:8
PRE_SEQ_LEN=512
LR=2e-2
NUM_GPUS=8

torchrun --standalone --nnodes 1 --nproc_per_node $NUM_GPUS main.py \
    --do_train \
    --train_file dataset/train_v2.json \
    --validation_file dataset/test_v2.json \
    --preprocessing_num_workers 10 \
    --prompt_column info \
    --response_column label \
    --overwrite_cache \
    --model_name_or_path ../chatglm2-6b \
    --output_dir output/cve-chatglm2-6b-cls-$PRE_SEQ_LEN-$LR \
    --overwrite_output_dir \
    --max_source_length 512 \
    --max_target_length 16 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 12 \
    --predict_with_generate \
    --max_steps 2000 \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate $LR \
    --pre_seq_len $PRE_SEQ_LEN \
    --quantization_bit 8

```

### Environment

```markdown
- OS: CentOS 7.9
- Python: 3.10
- Transformers: 4.29.0
- PyTorch: 1.12.1
- CUDA Support: True
```

**Comment by ZCQ0628** [comment]
+1 我也有这个问题 请问解决了吗

**Comment by YXlukarov** [comment]
> 

没有，我把数据集的规模缩减之后再训练是可行的，缩减后的训练数据大概有16w条，用train.sh开int 8精度可以训练，用deepspeed fp16微调的时候又抱别的错误了

**Comment by ZCQ0628** [comment]
> > +1 我也有这个问题求解决了吗
> 
> ，我把数据集的规模缩减之后再训练是可行的，缩减后的数据大概有16w条，用train.sh开int 8精度训练可以，用deepspeed fp16调整的时候又抱其他错误了

我这个放了10条数据集 还是报这个错 整个人不好了

**Comment by YXlukarov** [comment]
> > > +1 我也有这个问题求解决了吗
> > 
> > 
> > ，我把数据集的规模缩减之后再训练是可行的，缩减后的数据大概有16w条，用train.sh开int 8精度训练可以，用deepspeed fp16调整的时候又抱其他错误了
> 
> 我这个放了10条数据集 还是报这个错 整个人不好了

没道理吧，把你的脚本贴出来看一下?
