### ISSUE TITLE
[BUG/Help] cannot import name '_sentencepiece' from partially initialized module 'sentencepiece'

### ISSUE THREAD

**Issue by mericalandintent** [THUDM/ChatGLM2-6B#662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

C:\Users\Lee\source\ChatGLM2-6B\web_demo.py:46: SyntaxWarning: invalid escape sequence '\`'
  line = line.replace("`", "\`")
Traceback (most recent call last):
  File "C:\Users\Lee\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\utils\import_utils.py", line 1086, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lee\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Lee\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\models\__init__.py", line 15, in <module>
    from . import (
  File "C:\Users\Lee\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\models\mt5\__init__.py", line 29, in <module>
    from ..t5.tokenization_t5 import T5Tokenizer
  File "C:\Users\Lee\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\models\t5\tokenization_t5.py", line 24, in <module>
    import sentencepiece as spm
  File "C:\Users\Lee\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentencepiece\__init__.py", line 13, in <module>
    from . import _sentencepiece
ImportError: cannot import name '_sentencepiece' from partially initialized module 'sentencepiece' (most likely due to a circular import) (C:\Users\Lee\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentencepiece\__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lee\source\ChatGLM2-6B\web_demo.py", line 1, in <module>
    from transformers import AutoModel, AutoTokenizer
  File "<frozen importlib._bootstrap>", line 1406, in _handle_fromlist
  File "C:\Users\Lee\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\utils\import_utils.py", line 1076, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lee\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\utils\import_utils.py", line 1088, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.auto because of the following error (look up to see its traceback):
cannot import name '_sentencepiece' from partially initialized module 'sentencepiece' (most likely due to a circular import) (C:\Users\Lee\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentencepiece\__init__.py)

### Steps To Reproduce

in windows 11 run web_demo.py 

### Environment

```markdown
- OS: windows 11
- Python: 3.12
- Transformers: 4.30.2
- PyTorch: 2.2.0+cu121
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by Goku-xym** [comment]
I face the same issue, how can fix it ?

**Comment by KuijpersNick0** [comment]
Same issue

**Comment by Y1ran** [comment]
Same issue

**Comment by Y1ran** [comment]
I fixed it by 
`pip uninstall sentence_transformers`
then
`conda install sentence_transformers`

**Comment by ifdealer** [comment]
use this
conda install sentencepiece
