### ISSUE TITLE
[Help] 启动web_demo报错，加载tokenizer报错

### ISSUE THREAD

**Issue by majijia505** [THUDM/ChatGLM2-6B#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

使用最新的代码加载本地模型是报错  tokenizer报错
Traceback (most recent call last):
  File "/AI/models/ChatGLM2-6B-main/web_demo.py", line 7, in <module>
    tokenizer = AutoTokenizer.from_pretrained("/AI/models/ChatGLM2-6B-main/models/chatglm2-6b", trust_remote_code=True  )
  File "/AI/anaconda3/envs/chatglm2/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 678, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/AI/anaconda3/envs/chatglm2/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
    return cls._from_pretrained(
  File "/AI/anaconda3/envs/chatglm2/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1988, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/appuser/.cache/huggingface/modules/transformers_modules/chatglm2-6b/tokenization_chatglm.py", line 73, in __init__
    self.tokenizer = SPTokenizer(vocab_file)
  File "/home/appuser/.cache/huggingface/modules/transformers_modules/chatglm2-6b/tokenization_chatglm.py", line 14, in __init__
    self.sp_model = SentencePieceProcessor(model_file=model_path)
  File "/AI/anaconda3/envs/chatglm2/lib/python3.10/site-packages/sentencepiece/__init__.py", line 447, in Init
    self.Load(model_file=model_file, model_proto=model_proto)
  File "/AI/anaconda3/envs/chatglm2/lib/python3.10/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/AI/anaconda3/envs/chatglm2/lib/python3.10/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]

### Steps To Reproduce

1、conda create -n chatglm2 python=3.10.6 
2、conda activate chatglm2
3、pip install -r requirements.txt
4、pip install gradio 
5、修改web_demo.py 加载本地模型路径

### Environment

```markdown
- OS: centos 7.4 
- Python: python 3.10.6 
- Transformers: 4.30.2
- PyTorch: 2.0.1 
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) : True
```

**Comment by zj23564** [comment]
遇到同样的问题

**Comment by zj23564** [comment]
已解决，没注意下载的模型文件大小。
tokenizer.model这个文件，重新去下载，然后覆盖。

**Comment by majijia505** [comment]
感谢  已解决  不知道为啥git clone的 tokenizer.model文件有问题
