### ISSUE TITLE
[Feature] <title>RuntimeError: Expected is_sm8x || is_sm75 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

### ISSUE THREAD

**Issue by Jerryzxxxxx** [THUDM/ChatGLM2-6B#98]
### Is your feature request related to a problem? Please describe.

启动chatglm2-6b后，在页面问答时报错这个，如果解决啊

### Solutions

给条明路吧

### Additional context

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gradio/routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.9/site-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.9/site-packages/gradio/blocks.py", line 1035, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.9/site-packages/gradio/utils.py", line 491, in async_iteration
    return next(iterator)
  File "/root/ChatGLM2-6B-main/web_demo.py", line 65, in predict
    for response, history, past_key_values in model.stream_chat(tokenizer, input, history, past_key_values=past_key_values,
  File "/usr/local/lib64/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py", line 976, in stream_chat
    for outputs in self.stream_generate(**inputs, past_key_values=past_key_values,
  File "/usr/local/lib64/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py", line 1061, in stream_generate
    outputs = self(
  File "/usr/local/lib64/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py", line 848, in forward
    transformer_outputs = self.transformer(
  File "/usr/local/lib64/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py", line 744, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "/usr/local/lib64/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py", line 588, in forward
    hidden_states, kv_cache = layer(
  File "/usr/local/lib64/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py", line 510, in forward
    attention_output, kv_cache = self.self_attention(
  File "/usr/local/lib64/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py", line 407, in forward
    context_layer = self.core_attention(query_layer, key_layer, value_layer, attention_mask)
  File "/usr/local/lib64/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py", line 192, in forward
    context_layer = torch.nn.functional.scaled_dot_product_attention(query_layer, key_layer, value_layer,
RuntimeError: Expected is_sm8x || is_sm75 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

**Comment by amj12321** [comment]
看这个报错应该是你的显卡架构太老了，无法运行这个库[https://pypi.org/project/flash-attn/](url)，sm8x和sm75应该指必须是图灵架构以上的显卡[https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/](url)

**Comment by duzx16** [comment]
应该是 pytorch 的 `scaled_dot_product_attention` 实现的问题
可以先将 pytorch 降级到 2.0以下的版本，或者尝试安装最新版的 `pytorch-nightly`

**Comment by Yshihui** [comment]
遇到同样问题，

**Comment by MeliodasA3** [comment]
> encountered the same problem,

Have you solved it?

**Comment by SH0AN** [comment]
有人解决这个问题？

**Comment by SH0AN** [comment]
我找到解决方案了，程序开头加入：
import torch
torch.backends.cuda.enable_flash_sdp(False)
即可！
