### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by su-heyang** [THUDM/ChatGLM2-6B#99]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

当我使用本地模型文件路径时，代码仍然去找.cache/huggingface下的chatglm2-6b模型文件，从而报出文件找不到的情况

### Steps To Reproduce

run `python cli_demo.py`
error:
Traceback (most recent call last):
  File "web_demo.py", line 6, in <module>
    tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True)
  File "/home/admin/anaconda3/envs/glm2/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 678, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/admin/anaconda3/envs/glm2/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
    return cls._from_pretrained(
  File "/home/admin/anaconda3/envs/glm2/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1988, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/admin/.cache/huggingface/modules/transformers_modules/chatglm2-6b/tokenization_chatglm.py", line 73, in __init__
    self.tokenizer = SPTokenizer(vocab_file)
  File "/home/admin/.cache/huggingface/modules/transformers_modules/chatglm2-6b/tokenization_chatglm.py", line 13, in __init__
    assert os.path.isfile(model_path), model_path
  File "/home/admin/anaconda3/envs/glm2/lib/python3.8/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### Environment

```markdown
- OS:Ubuntu 18.04
- Python:3.8
- Transformers:4.30.2
- PyTorch:2.0.1
- CUDA Support (`python -c "import torch; print(torch.cuda.is_available())"`) :True
```

**Comment by duzx16** [comment]
`tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True)` 这一句用的不是你本地的路径
